"""Fit monotone reflectron ring voltages to the ideal piecewise-linear axis potential."""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import numpy as np
from scipy.optimize import LinearConstraint, minimize


def render_lua_profile(result: dict) -> str:
    def values(items: list[float]) -> str:
        return ", ".join(format(float(item), ".17g") for item in items)

    return (
        "-- Generated by optimize_reflectron_ring_voltages.py; do not edit manually.\n"
        "return {\n"
        f"  schema_version = {int(result['schema_version'])},\n"
        f"  stage1_count = {int(result['stage1_count'])},\n"
        f"  stage2_count = {int(result['stage2_count'])},\n"
        "  stage1_ring_voltages_V = {"
        + values(result["stage1_ring_voltages_V"])
        + "},\n"
        "  stage2_ring_voltages_V = {"
        + values(result["stage2_ring_voltages_V"])
        + "},\n}\n"
    )


def _load_basis(path: Path) -> tuple[np.ndarray, np.ndarray]:
    with path.open("r", encoding="utf-8", newline="") as stream:
        rows = list(csv.DictReader(stream))
    x = np.asarray([float(row["x_mm"]) for row in rows])
    columns = [name for name in rows[0] if name.startswith("basis_")]
    basis = np.asarray([[float(row[name]) / 10000.0 for name in columns] for row in rows])
    return x, basis


def optimize(
    x: np.ndarray,
    basis: np.ndarray,
    *,
    stage1_count: int,
    stage2_count: int,
    stage1_length_mm: float,
    stage2_length_mm: float,
    midgrid_voltage_v: float,
    backplate_voltage_v: float,
    regularization: float,
) -> dict:
    maximum_electrode = 4 + stage1_count + stage2_count
    if basis.shape[1] != maximum_electrode:
        raise ValueError("basis electrode count does not match ring counts")
    midgrid_electrode = 2 + stage1_count
    backplate_electrode = 3 + stage1_count + stage2_count
    variable_electrodes = [
        *range(2, midgrid_electrode),
        *range(midgrid_electrode + 1, backplate_electrode),
    ]
    fixed = (
        basis[:, midgrid_electrode - 1] * midgrid_voltage_v
        + basis[:, backplate_electrode - 1] * backplate_voltage_v
    )
    target = np.where(
        x <= stage1_length_mm,
        midgrid_voltage_v * x / stage1_length_mm,
        midgrid_voltage_v
        + (backplate_voltage_v - midgrid_voltage_v)
        * (x - stage1_length_mm)
        / stage2_length_mm,
    )
    # Exclude exact grid/backplate planes while retaining their neighboring fringe fields.
    mask = (
        (x > 0.0)
        & (x < stage1_length_mm + stage2_length_mm)
        & (np.abs(x - stage1_length_mm) > 1e-9)
    )
    matrix = basis[mask][:, np.asarray(variable_electrodes) - 1]
    rhs = target[mask] - fixed[mask]
    stage1_initial = midgrid_voltage_v * np.arange(1, stage1_count + 1) / (stage1_count + 1)
    stage2_initial = midgrid_voltage_v + (
        (backplate_voltage_v - midgrid_voltage_v)
        * np.arange(1, stage2_count + 1)
        / (stage2_count + 1)
    )
    initial = np.concatenate((stage1_initial, stage2_initial))
    # Normalize by the error that is actually being optimized.  Using the
    # approximately kilovolt target-potential scale makes the initial
    # objective and gradient so small that SLSQP can accept the linear divider
    # without taking a step, even when a useful monotone correction exists.
    initial_residual = matrix @ initial - rhs
    scale = max(float(np.sqrt(np.mean(initial_residual * initial_residual))), 1e-9)

    difference = np.zeros((stage1_count - 1 + stage2_count - 1, initial.size))
    row = 0
    for start, count in ((0, stage1_count), (stage1_count, stage2_count)):
        for index in range(count - 1):
            difference[row, start + index] = -1.0
            difference[row, start + index + 1] = 1.0
            row += 1

    def objective(values: np.ndarray) -> float:
        residual = matrix @ values - rhs
        penalty = values - initial
        return float(
            np.mean(residual * residual) / (scale * scale)
            + regularization * np.mean(penalty * penalty) / (backplate_voltage_v**2)
        )

    def gradient(values: np.ndarray) -> np.ndarray:
        residual = matrix @ values - rhs
        return (
            2.0 * matrix.T @ residual / (residual.size * scale * scale)
            + 2.0
            * regularization
            * (values - initial)
            / (values.size * backplate_voltage_v**2)
        )

    result = minimize(
        objective,
        initial,
        jac=gradient,
        method="SLSQP",
        bounds=[(0.0, midgrid_voltage_v)] * stage1_count
        + [(midgrid_voltage_v, backplate_voltage_v)] * stage2_count,
        constraints=[LinearConstraint(difference, 0.0, np.inf)],
        options={"ftol": 1e-12, "maxiter": 2000},
    )
    if not result.success:
        raise RuntimeError(f"monotone voltage optimization failed: {result.message}")
    optimized = result.x
    baseline_residual = initial_residual
    optimized_residual = matrix @ optimized - rhs
    return {
        "schema_version": 1,
        "role": "oatof_reflectron_monotone_axis_field_voltage_fit",
        "status": "success",
        "stage1_count": stage1_count,
        "stage2_count": stage2_count,
        "fixed_endpoints_V": {
            "entrance": 0.0,
            "midgrid": midgrid_voltage_v,
            "backplate": backplate_voltage_v,
            "shield": 0.0,
        },
        "stage1_ring_voltages_V": optimized[:stage1_count].tolist(),
        "stage2_ring_voltages_V": optimized[stage1_count:].tolist(),
        "baseline_stage1_ring_voltages_V": stage1_initial.tolist(),
        "baseline_stage2_ring_voltages_V": stage2_initial.tolist(),
        "fit": {
            "sample_count": int(mask.sum()),
            "regularization": regularization,
            "baseline_axis_potential_rms_error_V": float(np.sqrt(np.mean(baseline_residual**2))),
            "optimized_axis_potential_rms_error_V": float(np.sqrt(np.mean(optimized_residual**2))),
            "maximum_voltage_change_V": float(np.max(np.abs(optimized - initial))),
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--basis-csv", type=Path, required=True)
    parser.add_argument("--contract", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--lua-output", type=Path)
    parser.add_argument("--regularization", type=float, default=1e-4)
    args = parser.parse_args()
    contract = json.loads(args.contract.read_text(encoding="utf-8"))
    x, basis = _load_basis(args.basis_csv)
    result = optimize(
        x,
        basis,
        stage1_count=int(contract["rings"]["stage1_count"]),
        stage2_count=int(contract["rings"]["stage2_count"]),
        stage1_length_mm=float(contract["geometry_mm"]["L_stage1"]),
        stage2_length_mm=float(contract["geometry_mm"]["L_stage2"]),
        midgrid_voltage_v=float(contract["electrodes_V"]["midgrid"]),
        backplate_voltage_v=float(contract["electrodes_V"]["backplate"]),
        regularization=args.regularization,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    if args.lua_output is not None:
        args.lua_output.parent.mkdir(parents=True, exist_ok=True)
        args.lua_output.write_text(render_lua_profile(result), encoding="utf-8", newline="\n")
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
