function timing = configure_oatof_segmented_output(model, mass_amu, fine_step_ns, drift_step_ns, contract)
%CONFIGURE_OATOF_SEGMENTED_OUTPUT Persist GUI-visible oa-TOF time windows.
% Event times are derived from the same mass, voltage and length parameters
% used by the physical model. Fine-window boundaries are aligned to one
% global fine-step lattice; changing that phase was proven to change the
% deterministic COMSOL trajectory even when every force region was covered.

arguments
    model
    mass_amu (1,1) double {mustBePositive}
    fine_step_ns (1,1) double {mustBePositive}
    drift_step_ns (1,1) double {mustBePositive}
    contract = []
end

p = model.param;
if nargin < 5 || isempty(contract)
    contract = load_oatof_contract();
end
runtime = contract.comsol_runtime;
p.set('ion_mass_amu', sprintf('%.12g', mass_amu), ...
    'Reference ion mass number for GUI-visible event-time formulas');
p.set('ion_mass_ref', 'ion_mass_amu*1.66053906660e-27[kg]', ...
    'Reference ion mass used by event-time formulas');
p.set('ion_charge_ref', '1.602176634e-19[C]', ...
    'Singly charged reference ion');
p.set('source_z_ref', 'source_center_z', ...
    'Center of the release interval, linked to the canonical repeller datum');
p.set('accel_stage1_end', 'z_accel_grid1', ...
    'First accelerator-grid global z coordinate');
p.set('a_accel1_ref', ...
    ['ion_charge_ref*(V_repeller-V_grid1)/' ...
     '((accel_stage1_end-z_accel_origin)*ion_mass_ref)']);
p.set('t_accel1_ref', ...
    'sqrt(2*(accel_stage1_end-source_z_ref)/a_accel1_ref)');
p.set('v_accel1_ref', 'a_accel1_ref*t_accel1_ref');
p.set('a_accel2_ref', ...
    'ion_charge_ref*V_grid1/((z_accel_grid2-accel_stage1_end)*ion_mass_ref)');
p.set('t_accel2_ref', ...
    ['(sqrt(v_accel1_ref^2+2*a_accel2_ref*' ...
     '(z_accel_grid2-accel_stage1_end))-v_accel1_ref)/a_accel2_ref']);
p.set('v_flight_ref', 'v_accel1_ref+a_accel2_ref*t_accel2_ref');
p.set('t_accel_exit_ref', 't_accel1_ref+t_accel2_ref');
p.set('t_refl_entry_ref', ...
    't_accel_exit_ref+(L_flight-z_accel_grid2)/v_flight_ref');
p.set('a_refl1_ref', 'ion_charge_ref*V_mid/(L_stage1*ion_mass_ref)');
p.set('v_refl_stage2_ref', ...
    'sqrt(v_flight_ref^2-2*a_refl1_ref*L_stage1)');
p.set('t_refl_stage1_ref', ...
    '(v_flight_ref-v_refl_stage2_ref)/a_refl1_ref');
p.set('a_refl2_ref', ...
    ['ion_charge_ref*(V_mirror-V_mid)/' ...
     '((L_refl-L_stage1)*ion_mass_ref)']);
p.set('t_refl_stage2_turn_ref', 'v_refl_stage2_ref/a_refl2_ref');
p.set('t_refl_exit_ref', ...
    't_refl_entry_ref+2*(t_refl_stage1_ref+t_refl_stage2_turn_ref)');
p.set('t_detector_ref', ...
    't_refl_exit_ref+(L_flight-detector_z)/v_flight_ref');

p.set('cpt_dt_fine', sprintf('%.12g[ns]', fine_step_ns), ...
    'Fine GUI output step in accelerator, reflectron and detector windows');
p.set('cpt_dt_drift', sprintf('%.12g[ns]', drift_step_ns), ...
    'Coarse GUI output step in field-free drift windows');
p.set('cpt_accel_margin', sprintf('%.12g[us]', runtime.accelerator_window_margin_us), ...
    'Safety margin after predicted accelerator exit');
p.set('cpt_refl_margin', sprintf('%.12g[us]', runtime.reflectron_window_margin_us), ...
    'Safety margin on both sides of predicted reflectron transit');
p.set('cpt_detector_margin', sprintf('%.12g[us]', runtime.detector_window_margin_us), ...
    'Safety margin on both sides of predicted detector arrival');

% Outward rounding preserves coverage and locks every fine segment to the
% global t=0 phase. Do not replace these with the unrounded raw times.
p.set('cpt_t_accel_end_raw', 't_accel_exit_ref+cpt_accel_margin');
p.set('cpt_t_accel_end', ...
    'ceil(cpt_t_accel_end_raw/cpt_dt_fine)*cpt_dt_fine');
p.set('cpt_t_refl_start_raw', ...
    'max(cpt_t_accel_end,t_refl_entry_ref-cpt_refl_margin)');
p.set('cpt_t_refl_start', ...
    'floor(cpt_t_refl_start_raw/cpt_dt_fine)*cpt_dt_fine');
p.set('cpt_t_refl_end_raw', 't_refl_exit_ref+cpt_refl_margin');
p.set('cpt_t_refl_end', ...
    'ceil(cpt_t_refl_end_raw/cpt_dt_fine)*cpt_dt_fine');
p.set('cpt_t_detector_start_raw', ...
    'max(cpt_t_refl_end,t_detector_ref-cpt_detector_margin)');
p.set('cpt_t_detector_start', ...
    'floor(cpt_t_detector_start_raw/cpt_dt_fine)*cpt_dt_fine');
p.set('cpt_t_detector_end_raw', ...
    't_detector_ref+cpt_detector_margin');
p.set('cpt_t_detector_end', ...
    'ceil(cpt_t_detector_end_raw/cpt_dt_fine)*cpt_dt_fine');
p.set('cpt_t_end', 'cpt_t_detector_end+1[us]', ...
    'GUI-visible simulation end after the predicted detector window');

tlist = [ ...
    'range(0,cpt_dt_fine,cpt_t_accel_end) ' ...
    'range(cpt_t_accel_end+cpt_dt_drift,cpt_dt_drift,cpt_t_refl_start) ' ...
    'cpt_t_refl_start ' ...
    'range(cpt_t_refl_start+cpt_dt_fine,cpt_dt_fine,cpt_t_refl_end) ' ...
    'range(cpt_t_refl_end+cpt_dt_drift,cpt_dt_drift,cpt_t_detector_start) ' ...
    'cpt_t_detector_start ' ...
    'range(cpt_t_detector_start+cpt_dt_fine,cpt_dt_fine,cpt_t_detector_end) ' ...
    'range(cpt_t_detector_end+cpt_dt_drift,cpt_dt_drift,cpt_t_end)'];
model.study('std2').feature('time1').set('tlist', tlist);

cpt = model.component('comp1').physics('cpt');
cpt.prop('StoreExtra').set('StoreExtra', false);
cpt.prop('StoreParticleStatusData').set('StoreParticleStatusData', false);

timing = struct;
timing.tlist = tlist;
timing.expected_tof_s = mphevaluate(model, 't_detector_ref', 's');
timing.t_accel_end_s = mphevaluate(model, 'cpt_t_accel_end', 's');
timing.t_refl_start_s = mphevaluate(model, 'cpt_t_refl_start', 's');
timing.t_refl_end_s = mphevaluate(model, 'cpt_t_refl_end', 's');
timing.t_detector_start_s = ...
    mphevaluate(model, 'cpt_t_detector_start', 's');
timing.t_detector_end_s = mphevaluate(model, 'cpt_t_detector_end', 's');
timing.t_end_s = mphevaluate(model, 'cpt_t_end', 's');
end
