function accelringtags = oatof_build_accelerator_geometry(geom1, acceleratorRingCount, interfacePort)
% REPOSITORY_CONTRACT: MATLAB_BUILD_ONLY
%OATOF_BUILD_ACCELERATOR_GEOMETRY Map instrument expressions to the component API.
% The independent project owns solid construction. Existing COMSOL feature tags
% and instrument parameters are retained for downstream selections and CAD.
if nargin < 3
    interfacePort = struct('enabled', false);
end
layout = struct( ...
    'ring_count', acceleratorRingCount, ...
    'x_center', 'x_accel_center', 'y_center', '0', ...
    'repeller_front_z', 'z_accel_origin', ...
    'electrode_half_width', 'accel_shield_half-accel_ring_gap', ...
    'repeller_thickness', 'accel_repeller_thickness', ...
    'shield_inner_half_width', 'accel_shield_half', ...
    'shield_wall', 'accel_shield_wall', ...
    'total_length', 'L_accel', 'rear_gap', 'accel_shield_back_extra', ...
    'grid1_z', 'z_accel_grid1', 'stage2_length', 'accel_stage2_length', ...
    'ring_bore_half_width', 'accel_ring_bore_half', ...
    'ring_thickness', 'accel_ring_thickness', ...
    'grid1_voltage', 'V_grid1', ...
    'boolean_cut_padding_mm', 0.1);
projectsRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
componentDir = fullfile(projectsRoot, 'orthogonal_accelerator', 'comsol');
previousPath = path;
restorePath = onCleanup(@() path(previousPath)); %#ok<NASGU>
addpath(componentDir);
accelringtags = build_two_zone_geometry(geom1, layout, interfacePort);
end
