function handoff = oatof_export_detector_events(results_dir,label,mass_amu,arrivals,initial_x_mm,initial_y_mm,initial_z_mm)
% Export solver-native per-particle detector events for Python analysis.
% This boundary deliberately contains no mean, width, fit, or peak metric.

assert(exist(results_dir,'dir') == 7, 'Results directory is missing: %s', results_dir);
count = numel(arrivals.hit);
assert(numel(initial_x_mm) == count && numel(initial_y_mm) == count && ...
    numel(initial_z_mm) == count, 'Initial coordinate count differs from event count.');
safe_label = regexprep(char(label), '[^A-Za-z0-9_-]', '_');
events_path = fullfile(results_dir, sprintf('comsol_detector_events_%s.csv', safe_label));
request_path = fullfile(results_dir, sprintf('comsol_detector_events_%s.analysis_request.json', safe_label));
analysis_output_dir = fullfile(results_dir, sprintf('comsol_detector_events_%s_analysis', safe_label));

events = table((1:count).', arrivals.time_s(:)*1e6, arrivals.x_mm(:), arrivals.y_mm(:), ...
    logical(arrivals.hit(:)), string(arrivals.status(:)), string(arrivals.event(:)), ...
    arrivals.radius_mm(:), initial_x_mm(:), initial_y_mm(:), initial_z_mm(:), ...
    'VariableNames', {'Ion','TofUs','XMm','YMm','Hit','Status','Event', ...
    'DetectorRadiusMm','X0Mm','Y0Mm','Z0Mm'});
writetable(events, events_path);

request = struct( ...
    'schema_version', 1, ...
    'role', 'oatof_comsol_detector_events_analysis_request', ...
    'solver', 'COMSOL', ...
    'label', char(label), ...
    'nominal_mass_Da', mass_amu, ...
    'raw_events_csv', events_path, ...
    'analysis_output_dir', analysis_output_dir, ...
    'event_extraction', 'solver_native_detector_crossing_or_freeze', ...
    'aggregate_metrics_owner', 'python_reference_analysis');
fid = fopen(request_path, 'w');
assert(fid >= 0, 'Could not write Python analysis request: %s', request_path);
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', jsonencode(request));
clear cleanup

handoff = struct('events_path', events_path, 'request_path', request_path, ...
    'analysis_output_dir', analysis_output_dir, 'particle_count', count);
fprintf('[%s] exported %d solver-native detector events for Python analysis: %s\n', ...
    label, count, events_path);
end
