% Solve the full RF field on topology-aligned piecewise swept prism segments.
reportPath=getenv('COMSOL_BOOTSTRAP_REPORT');outputCsv=getenv('RF_PIECEWISE_FIELD_CSV');contractPath=getenv('RF_PIECEWISE_CONTRACT');resolvedPath=getenv('RF_PIECEWISE_RESOLVED');profile=getenv('RF_PIECEWISE_PROFILE');assert(any(strcmp(profile,{'coarse','fine'})),'Unknown piecewise profile.');fid=fopen(reportPath,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'TASK=RF_PIECEWISE_SWEPT_MESH\nPROFILE=%s\n',profile);
try
 c=jsondecode(fileread(contractPath));resolved=jsondecode(fileread(resolvedPath));g=resolved.geometry_mm;interfaces=resolved.interfaces_mm;geo=c.geometry_mm;tm=c.transverse_mesh;am=c.axial_mesh;if strcmp(profile,'coarse'),layers=am.coarse_layer_count_by_segment(:);else,layers=am.fine_layer_count_by_segment(:);end
 import com.comsol.model.*
 import com.comsol.model.util.*
 tag='RF_PIECEWISE';if any(strcmp(cell(ModelUtil.tags()),tag)),ModelUtil.remove(tag);end;model=ModelUtil.create(tag);comp=model.component.create('comp1',true);geom=comp.geom.create('geom1',3);geom.lengthUnit('mm');wall=1.0;bounds=geo.segment_boundaries_z(:);
 add_cylinder(geom,'vac',geo.shield_inner_radius,bounds(end)-bounds(1),bounds(1),true);add_cylinder(geom,'core',geo.fine_core_radius,bounds(end)-bounds(1),bounds(1),true);segmentTags=cell(1,numel(bounds)-1);for i=1:numel(segmentTags),segmentTags{i}=sprintf('seg%d',i);add_cylinder(geom,segmentTags{i},geo.shield_inner_radius,bounds(i+1)-bounds(i),bounds(i),true);end
 rodTags=cell(1,4);for i=1:4,rodTags{i}=sprintf('rod%d',i);angle=(i-1)*90;geom.feature.create(rodTags{i},'Cylinder');geom.feature(rodTags{i}).set('r',sprintf('%.17g[mm]',g.rod_radius));geom.feature(rodTags{i}).set('h',sprintf('%.17g[mm]',g.rod_length));geom.feature(rodTags{i}).set('pos',{sprintf('%.17g[mm]',g.rod_center_radius*cosd(angle)),sprintf('%.17g[mm]',g.rod_center_radius*sind(angle)),sprintf('%.17g[mm]',g.rod_z_min)});geom.feature(rodTags{i}).set('selresult','on');end
 % Mesh-control imprints continue both the aperture circle and rod footprints
 % through the two vacuum transition segments. They remain vacuum domains.
 add_cylinder(geom,'imprintApertureIn',interfaces.entrance.aperture_radius_mm,g.rod_z_min-interfaces.entrance.plate_z_max_mm,interfaces.entrance.plate_z_max_mm,false);add_cylinder(geom,'imprintApertureOut',interfaces.exit.aperture_radius_mm,interfaces.exit.plate_z_min_mm-g.rod_z_max,g.rod_z_max,false);
 for i=1:4,angle=(i-1)*90;for side={'In','Out'},if strcmp(side{1},'In'),zStart=interfaces.entrance.plate_z_max_mm;height=g.rod_z_min-interfaces.entrance.plate_z_max_mm;else,zStart=g.rod_z_max;height=interfaces.exit.plate_z_min_mm-g.rod_z_max;end;tagImprint=sprintf('imprintRod%s%d',side{1},i);geom.feature.create(tagImprint,'Cylinder');geom.feature(tagImprint).set('r',sprintf('%.17g[mm]',g.rod_radius));geom.feature(tagImprint).set('h',sprintf('%.17g[mm]',height));geom.feature(tagImprint).set('pos',{sprintf('%.17g[mm]',g.rod_center_radius*cosd(angle)),sprintf('%.17g[mm]',g.rod_center_radius*sind(angle)),sprintf('%.17g[mm]',zStart)});end,end
 add_cylinder(geom,'shieldO',geo.shield_inner_radius+wall,interfaces.exit.plate_z_min_mm-interfaces.entrance.plate_z_max_mm,interfaces.entrance.plate_z_max_mm,false);add_cylinder(geom,'shieldH',geo.shield_inner_radius,interfaces.exit.plate_z_min_mm-interfaces.entrance.plate_z_max_mm,interfaces.entrance.plate_z_max_mm,false);geom.feature.create('shield','Difference');geom.feature('shield').selection('input').set({'shieldO'});geom.feature('shield').selection('input2').set({'shieldH'});geom.feature('shield').set('selresult','on');add_annular_plate(geom,'entrance',geo.shield_inner_radius+wall,interfaces.entrance.aperture_radius_mm,interfaces.entrance.plate_z_min_mm,interfaces.entrance.plate_z_max_mm-interfaces.entrance.plate_z_min_mm);add_annular_plate(geom,'exit',geo.shield_inner_radius+wall,interfaces.exit.aperture_radius_mm,interfaces.exit.plate_z_min_mm,interfaces.exit.plate_z_max_mm-interfaces.exit.plate_z_min_mm);geom.run;
 solidTags=[rodTags,{'shield','entrance','exit'}];solidDomains=cellfun(@(name)['geom1_' name '_dom'],solidTags,'UniformOutput',false);comp.selection.create('sel_vac','Complement');comp.selection('sel_vac').set('input',solidDomains);for i=1:numel(segmentTags),make_intersection(comp,sprintf('sel_seg%d_vac',i),{'sel_vac',['geom1_' segmentTags{i} '_dom']});make_intersection(comp,sprintf('sel_seg%d_core_vac',i),{sprintf('sel_seg%d_vac',i),'geom1_core_dom'});end
 material=model.material.create('mat_vac','Common');material.selection.named('sel_vac');material.propertyGroup('def').set('relpermittivity',{'1'});for i=1:numel(solidTags),name=solidTags{i};comp.selection.create(['selb_' name],'Adjacent');comp.selection(['selb_' name]).set('input',{['geom1_' name '_dom']});end
 es=comp.physics.create('es','Electrostatics','geom1');es.selection.named('sel_vac');for i=1:4,p=es.create(sprintf('pot_rod%d',i),'ElectricPotential',2);p.selection.named(sprintf('selb_rod%d',i));p.set('V0',sprintf('%d[V]',100*(-1)^(i+1)));end;for item={'shield','entrance','exit'},p=es.create(['pot_' item{1}],'ElectricPotential',2);p.selection.named(['selb_' item{1}]);p.set('V0','0[V]');end
 mesh=comp.mesh.create('mesh1');mesh.feature('size').set('hauto',6);for i=1:numel(segmentTags),sweep=mesh.feature.create(sprintf('swe%d',i),'Sweep');sweep.selection.geom('geom1',3);sweep.selection.named(sprintf('sel_seg%d_vac',i));sweep.set('facemethod','tri');add_size(sweep,'szOuter','geom1',3,sprintf('sel_seg%d_vac',i),tm.outer_vacuum_hmax_mm,tm.minimum_element_size_mm);add_size(sweep,'szCore','geom1',3,sprintf('sel_seg%d_core_vac',i),tm.fine_core_and_rod_boundary_hmax_mm,tm.minimum_element_size_mm);for rod=1:4,add_size(sweep,sprintf('szRod%d',rod),'geom1',2,sprintf('selb_rod%d',rod),tm.fine_core_and_rod_boundary_hmax_mm,tm.minimum_element_size_mm);end;dist=sweep.feature.create('dist1','Distribution');dist.selection.geom('geom1',3);dist.selection.named(sprintf('sel_seg%d_vac',i));dist.set('type','number');dist.set('numelem',round(layers(i)));dist.set('equidistant','on');end
 mesh.run;mi=mphmeshstats(model,'mesh1');vi=mphmeshstats(model,'mesh1','selection','sel_vac');fprintf(fid,'MESH_HASPROBLEMS=%d\nVACUUM_HASPROBLEMS=%d\nVACUUM_TOTAL_ELEMENTS=%d\n',mi.hasproblems,vi.hasproblems,sum(vi.numelem));for i=1:numel(segmentTags),si=mphmeshstats(model,'mesh1','selection',sprintf('sel_seg%d_vac',i));fprintf(fid,'SEGMENT_%d_ELEMENTS=%d\nSEGMENT_%d_LAYERS=%d\n',i,sum(si.numelem),i,layers(i));end;assert(~mi.hasproblems&&~vi.isempty&&~vi.hasproblems,'Piecewise swept mesh gate failed.');
 study=model.study.create('std1');study.create('stat','Stationary');sol=model.sol.create('sol1');sol.study('std1');sol.createAutoSequence('std1');sol.attach('std1');sol.runAll;s=c.field_sampling;fractions=s.sample_radius_fraction_of_r0(:);zValues=s.sample_z_mm(:);nTheta=s.azimuth_samples_per_radius;theta=(0:nTheta-1)'*(2*pi/nTheta);radius=[];thetaAll=[];zAll=[];for iz=1:numel(zValues),for ir=1:numel(fractions),radius=[radius;repmat(fractions(ir)*g.inscribed_radius_r0,nTheta,1)];thetaAll=[thetaAll;theta];zAll=[zAll;repmat(zValues(iz),nTheta,1)];end,end %#ok<AGROW>
 x=radius.*cos(thetaAll);y=radius.*sin(thetaAll);[V,Ex,Ey,Ez]=mphinterp(model,{'V','-d(V,x)','-d(V,y)','-d(V,z)'},'coord',[x.';y.';zAll.'],'dataset','dset1','matherr','on');assert(all(isfinite(V))&&all(isfinite(Ex))&&all(isfinite(Ey))&&all(isfinite(Ez)),'Piecewise field sampling incomplete.');samples=table(repmat(geo.shield_inner_radius,numel(x),1),repmat(profile,numel(x),1),zAll,zAll,radius,radius,thetaAll,x,y,V(:),Ex(:),Ey(:),Ez(:),'VariableNames',{'shield_inner_radius_mm','mesh_profile','sample_z_mm','evaluation_z_mm','sample_radius_mm','evaluation_radius_mm','theta_rad','x_mm','y_mm','potential_V','Ex_V_per_m','Ey_V_per_m','Ez_V_per_m'});outdir=fileparts(outputCsv);if~isfolder(outdir),mkdir(outdir);end;writetable(samples,outputCsv);fprintf(fid,'SAMPLE_ROWS=%d\nMODEL_SAVED=false\nSTATUS=PASS\n',height(samples));
catch exception
 fprintf(fid,'STATUS=FAIL\nERROR=%s\n',getReport(exception,'extended','hyperlinks','off'));
 rethrow(exception);
end
clear cleanup
function add_cylinder(geom,tag,radius,height,zStart,sel),geom.feature.create(tag,'Cylinder');geom.feature(tag).set('r',sprintf('%.17g[mm]',radius));geom.feature(tag).set('h',sprintf('%.17g[mm]',height));geom.feature(tag).set('pos',{'0','0',sprintf('%.17g[mm]',zStart)});if sel,geom.feature(tag).set('selresult','on');end,end
function add_annular_plate(geom,tag,outerRadius,holeRadius,zStart,thickness),add_cylinder(geom,[tag 'O'],outerRadius,thickness,zStart,false);add_cylinder(geom,[tag 'H'],holeRadius,thickness,zStart,false);geom.feature.create(tag,'Difference');geom.feature(tag).selection('input').set({[tag 'O']});geom.feature(tag).selection('input2').set({[tag 'H']});geom.feature(tag).set('selresult','on');end
function make_intersection(comp,tag,inputs),comp.selection.create(tag,'Intersection');comp.selection(tag).set('entitydim',3);comp.selection(tag).set('input',inputs);end
function add_size(parent,tag,geomTag,dim,sel,hmax,hmin),f=parent.feature.create(tag,'Size');f.selection.geom(geomTag,dim);f.selection.named(sel);f.set('custom','on');f.set('hmaxactive',true);f.set('hmax',sprintf('%.17g[mm]',hmax));f.set('hminactive',true);f.set('hmin',sprintf('%.17g[mm]',hmin));end
