% Build the S2 passive RF-to-oaTOF connector geometry without mesh or physics.
% REPOSITORY_CONTRACT: MATLAB_BUILD_ONLY

reportPath = getenv('COMSOL_BOOTSTRAP_REPORT');
metricsPath = getenv('RF_OATOF_S2_GEOMETRY_METRICS');
contractPath = getenv('RF_OATOF_S2_CONTRACT');
s1ContractPath = getenv('RF_OATOF_S2_S1_CONTRACT');
rfResolvedPath = getenv('RF_OATOF_S2_RF_RESOLVED');
oaBaselinePath = getenv('RF_OATOF_S2_OA_BASELINE');
oaComsolDir = getenv('RF_OATOF_S2_OA_COMSOL_DIR');
assert(~isempty(reportPath) && ~isempty(metricsPath), 'S2 output paths are incomplete.');
assert(isfile(contractPath) && isfile(s1ContractPath) && ...
    isfile(rfResolvedPath) && isfile(oaBaselinePath), ...
    'S2 contract inputs are incomplete.');
assert(isfolder(oaComsolDir), 'The oaTOF COMSOL source directory is missing.');

fid = fopen(reportPath, 'w');
assert(fid >= 0, 'Could not create the S2 COMSOL task report.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'TASK=S2_PASSIVE_CONNECTOR_GEOMETRY\n');

try
    contract = jsondecode(fileread(contractPath));
    s1 = jsondecode(fileread(s1ContractPath));
    rf = jsondecode(fileread(rfResolvedPath));
    oa = jsondecode(fileread(oaBaselinePath));
    assert(contract.permissions.geometry_builder_implementation_allowed, ...
        'The S2 contract does not authorize geometry construction.');
    import com.comsol.model.util.*
    tag = 'RFOATOF_S2_GEOMETRY';
    [model, context] = build_s2_passive_connector_model( ...
        contract, s1, rf, oa, oaComsolDir, tag);
    geometryInfo = mphgeominfo(model, 'geom1');

    metrics = struct( ...
        'schema_version', 1, ...
        'role', 'rf_to_oatof_s2_passive_connector_geometry_metrics', ...
        'status', 'BUILT', ...
        'gap_mm', context.gap_mm, ...
        'source_exit_center_instrument_mm', context.source_center_mm, ...
        'target_entry_center_instrument_mm', context.target_center_mm, ...
        'connector_inner_radius_mm', context.connector_inner_radius_mm, ...
        'oatof_port_full_width_y_mm', context.port_full_width_y_mm, ...
        'oatof_port_full_height_z_mm', context.port_full_height_z_mm, ...
        'rf_shield_inner_radius_mm', context.rf_shield_inner_radius_mm, ...
        'oatof_downstream_buffer_mm', context.oatof_downstream_buffer_mm, ...
        'geometry_domains', geometryInfo.Ndomains, ...
        'connector_domain_count', context.connector_domain_count, ...
        'port_domain_count', context.port_domain_count, ...
        'rf_vacuum_domain_count', context.rf_vacuum_domain_count, ...
        'oatof_vacuum_domain_count', context.oatof_vacuum_domain_count, ...
        'mesh_built', false, ...
        'physics_created', false, ...
        'field_solved', false, ...
        'particle_runtime_executed', false, ...
        'model_saved', false, ...
        'claim_limit', 'Build-only S2 candidate geometry; no field, transport, stage PASS or Formal claim.');
    metricsDir = fileparts(metricsPath);
    if ~isfolder(metricsDir), mkdir(metricsDir); end
    metricsFid = fopen(metricsPath, 'w');
    assert(metricsFid >= 0, 'Could not create S2 geometry metrics.');
    fprintf(metricsFid, '%s', jsonencode(metrics, 'PrettyPrint', true));
    fclose(metricsFid);
    fprintf(fid, ['GAP_MM=%.17g\nCONNECTOR_DOMAINS=%d\nPORT_DOMAINS=%d\n' ...
        'GEOMETRY_DOMAINS=%d\nMESH_BUILT=false\nPHYSICS_CREATED=false\n' ...
        'FIELD_SOLVED=false\nPARTICLE_RUNTIME=false\nMODEL_SAVED=false\nSTATUS=PASS\n'], ...
        context.gap_mm, context.connector_domain_count, context.port_domain_count, geometryInfo.Ndomains);
    ModelUtil.remove(tag);
catch exception
    fprintf(fid, 'STATUS=FAIL\nERROR=%s\n', ...
        getReport(exception, 'extended', 'hyperlinks', 'off'));
    rethrow(exception)
end
clear cleanup
