% Build and solve the full RF device with swept central and tetrahedral end meshes.

reportPath=getenv('COMSOL_BOOTSTRAP_REPORT');outputCsv=getenv('RF_HYBRID_FIELD_CSV');contractPath=getenv('RF_HYBRID_CONTRACT');resolvedPath=getenv('RF_HYBRID_RESOLVED');shieldContractPath=getenv('RF_HYBRID_SHIELD_CONTRACT');endHmax=str2double(getenv('RF_HYBRID_END_HMAX_MM'));
particleTablePath=getenv('RF_HYBRID_PARTICLE_TABLE');particleEventsCsv=getenv('RF_HYBRID_PARTICLE_EVENTS_CSV');particleSummaryJson=getenv('RF_HYBRID_PARTICLE_SUMMARY_JSON');particleRuntimeDir=getenv('RF_HYBRID_PARTICLE_RUNTIME_DIR');particleEnabled=~isempty(particleTablePath);
assert(~isempty(reportPath)&&~isempty(outputCsv)&&~isempty(contractPath)&&~isempty(resolvedPath),'RF hybrid mesh environment is incomplete.');
fid=fopen(reportPath,'w');assert(fid>=0,'Could not create task report.');cleanup=onCleanup(@()fclose(fid));fprintf(fid,'TASK=RF_HYBRID_MESH\nEND_CORE_HMAX_MM=%.17g\n',endHmax);
try
    contract=jsondecode(fileread(contractPath));resolved=jsondecode(fileread(resolvedPath));g=resolved.geometry_mm;interfaces=resolved.interfaces_mm;geometry=contract.geometry_mm;uniformMesh=contract.uniform_region_mesh;endMesh=contract.end_region_mesh;
    if particleEnabled,assert(~isempty(shieldContractPath),'RF hybrid particle diagnostic lacks the shield transport contract.');shieldContract=jsondecode(fileread(shieldContractPath));transport=shieldContract.n100_transport_screen;end
    assert(any(abs(endMesh.fine_core_hmax_mm_sequence(:)-endHmax)<1e-12),'End hmax is outside the frozen sequence.');
    import com.comsol.model.*
    import com.comsol.model.util.*
    tag='RF_HYBRID';if any(strcmp(cell(ModelUtil.tags()),tag)),ModelUtil.remove(tag);end
    model=ModelUtil.create(tag);model.label(sprintf('RF hybrid mesh end hmax %.3g mm',endHmax));comp=model.component.create('comp1',true);geom=comp.geom.create('geom1',3);geom.lengthUnit('mm');wall=1.0;
    add_cylinder(geom,'vac',geometry.shield_inner_radius,geometry.model_z_max-geometry.model_z_min,geometry.model_z_min,true);
    add_cylinder(geom,'uniform',geometry.shield_inner_radius,geometry.uniform_region_z_max-geometry.uniform_region_z_min,geometry.uniform_region_z_min,true);
    add_cylinder(geom,'core',geometry.fine_core_radius,geometry.model_z_max-geometry.model_z_min,geometry.model_z_min,true);
    rodTags=cell(1,4);
    for index=1:4
        rodTags{index}=sprintf('rod%d',index);angle=(index-1)*90;geom.feature.create(rodTags{index},'Cylinder');geom.feature(rodTags{index}).set('r',sprintf('%.17g[mm]',g.rod_radius));geom.feature(rodTags{index}).set('h',sprintf('%.17g[mm]',g.rod_length));geom.feature(rodTags{index}).set('pos',{sprintf('%.17g[mm]',g.rod_center_radius*cosd(angle)),sprintf('%.17g[mm]',g.rod_center_radius*sind(angle)),sprintf('%.17g[mm]',g.rod_z_min)});geom.feature(rodTags{index}).set('selresult','on');
    end
    add_cylinder(geom,'shieldO',geometry.shield_inner_radius+wall,interfaces.exit.plate_z_min_mm-interfaces.entrance.plate_z_max_mm,interfaces.entrance.plate_z_max_mm,false);add_cylinder(geom,'shieldH',geometry.shield_inner_radius,interfaces.exit.plate_z_min_mm-interfaces.entrance.plate_z_max_mm,interfaces.entrance.plate_z_max_mm,false);
    geom.feature.create('shield','Difference');geom.feature('shield').selection('input').set({'shieldO'});geom.feature('shield').selection('input2').set({'shieldH'});geom.feature('shield').set('selresult','on');
    add_annular_plate(geom,'entrance',geometry.shield_inner_radius+wall,interfaces.entrance.aperture_radius_mm,interfaces.entrance.plate_z_min_mm,interfaces.entrance.plate_z_max_mm-interfaces.entrance.plate_z_min_mm);add_annular_plate(geom,'exit',geometry.shield_inner_radius+wall,interfaces.exit.aperture_radius_mm,interfaces.exit.plate_z_min_mm,interfaces.exit.plate_z_max_mm-interfaces.exit.plate_z_min_mm);geom.run;
    solidTags=[rodTags,{'shield','entrance','exit'}];solidDomains=cellfun(@(name)['geom1_' name '_dom'],solidTags,'UniformOutput',false);comp.selection.create('sel_vac','Complement');comp.selection('sel_vac').set('input',solidDomains);
    make_intersection(comp,'sel_uniform_vac',{'sel_vac','geom1_uniform_dom'});make_intersection(comp,'sel_core_vac',{'sel_vac','geom1_core_dom'});make_intersection(comp,'sel_uniform_core_vac',{'sel_uniform_vac','geom1_core_dom'});comp.selection.create('sel_end_vac','Difference');comp.selection('sel_end_vac').set('entitydim',3);comp.selection('sel_end_vac').set('add',{'sel_vac'});comp.selection('sel_end_vac').set('subtract',{'sel_uniform_vac'});make_intersection(comp,'sel_end_core_vac',{'sel_end_vac','geom1_core_dom'});
    material=model.material.create('mat_vac','Common');material.selection.named('sel_vac');material.propertyGroup('def').set('relpermittivity',{'1'});
    for index=1:numel(solidTags),name=solidTags{index};comp.selection.create(['selb_' name],'Adjacent');comp.selection(['selb_' name]).set('input',{['geom1_' name '_dom']});end
    es=comp.physics.create('es','Electrostatics','geom1');es.selection.named('sel_vac');for index=1:4,potential=es.create(sprintf('pot_rod%d',index),'ElectricPotential',2);potential.selection.named(sprintf('selb_rod%d',index));potential.set('V0',sprintf('%d[V]',100*(-1)^(index+1)));end
    for item={'shield','entrance','exit'},potential=es.create(['pot_' item{1}],'ElectricPotential',2);potential.selection.named(['selb_' item{1}]);potential.set('V0','0[V]');end
    mesh=comp.mesh.create('mesh1');mesh.feature('size').set('hauto',6);sweep=mesh.feature.create('swe1','Sweep');sweep.selection.geom('geom1',3);sweep.selection.named('sel_uniform_vac');sweep.set('facemethod','tri');
    add_size(sweep,'szUniformOuter','geom1',3,'sel_uniform_vac',uniformMesh.outer_vacuum_hmax_mm,0.02);add_size(sweep,'szUniformCore','geom1',3,'sel_uniform_core_vac',uniformMesh.fine_core_and_rod_boundary_hmax_mm,0.02);
    for index=1:4,add_size(sweep,sprintf('szUniformRod%d',index),'geom1',2,sprintf('selb_rod%d',index),uniformMesh.fine_core_and_rod_boundary_hmax_mm,0.02);end
    distribution=sweep.feature.create('dist1','Distribution');distribution.selection.geom('geom1',3);distribution.selection.named('sel_uniform_vac');distribution.set('type','number');distribution.set('numelem',round(uniformMesh.axial_layers));distribution.set('equidistant','on');
    ftet=mesh.feature.create('ftet1','FreeTet');ftet.selection.geom('geom1',3);ftet.selection.named('sel_end_vac');add_size(ftet,'szEndOuter','geom1',3,'sel_end_vac',endMesh.outer_vacuum_hmax_mm,0.02);add_size(ftet,'szEndCore','geom1',3,'sel_end_core_vac',endHmax,0.02);for index=1:4,add_size(ftet,sprintf('szEndRod%d',index),'geom1',2,sprintf('selb_rod%d',index),uniformMesh.fine_core_and_rod_boundary_hmax_mm,0.02);end
    mesh.run;meshInfo=mphmeshstats(model,'mesh1');vacuumInfo=mphmeshstats(model,'mesh1','selection','sel_vac');uniformInfo=mphmeshstats(model,'mesh1','selection','sel_uniform_vac');endInfo=mphmeshstats(model,'mesh1','selection','sel_end_vac');fprintf(fid,'GLOBAL_MESH_HASPROBLEMS=%d\nVACUUM_MESH_HASPROBLEMS=%d\nVACUUM_TOTAL_ELEMENTS=%d\nUNIFORM_TOTAL_ELEMENTS=%d\nEND_TOTAL_ELEMENTS=%d\n',meshInfo.hasproblems,vacuumInfo.hasproblems,sum(vacuumInfo.numelem),sum(uniformInfo.numelem),sum(endInfo.numelem));assert(~meshInfo.hasproblems&&~vacuumInfo.isempty&&~vacuumInfo.hasproblems&&~uniformInfo.isempty&&~endInfo.isempty,'RF hybrid vacuum mesh gate failed.');
    study=model.study.create('std1');study.create('stat','Stationary');solution=model.sol.create('sol1');solution.study('std1');solution.createAutoSequence('std1');solution.attach('std1');solution.runAll;
    sampling=contract.field_sampling;fractions=sampling.sample_radius_fraction_of_r0(:);zValues=sampling.sample_z_mm(:);nTheta=sampling.azimuth_samples_per_radius;theta=(0:nTheta-1)'*(2*pi/nTheta);radius=[];thetaAll=[];zAll=[];
    for zIndex=1:numel(zValues),for radiusIndex=1:numel(fractions),radius=[radius;repmat(fractions(radiusIndex)*g.inscribed_radius_r0,nTheta,1)];thetaAll=[thetaAll;theta];zAll=[zAll;repmat(zValues(zIndex),nTheta,1)];end,end %#ok<AGROW>
    x=radius.*cos(thetaAll);y=radius.*sin(thetaAll);[V,Ex,Ey,Ez]=mphinterp(model,{'V','-d(V,x)','-d(V,y)','-d(V,z)'},'coord',[x.';y.';zAll.'],'dataset','dset1','matherr','on');assert(all(isfinite(V))&&all(isfinite(Ex))&&all(isfinite(Ey))&&all(isfinite(Ez)),'RF hybrid field sampling is incomplete.');
    samples=table(repmat(geometry.shield_inner_radius,numel(x),1),repmat(endHmax,numel(x),1),zAll,zAll,radius,radius,thetaAll,x,y,V(:),Ex(:),Ey(:),Ez(:),'VariableNames',{'shield_inner_radius_mm','mesh_hmax_mm','sample_z_mm','evaluation_z_mm','sample_radius_mm','evaluation_radius_mm','theta_rad','x_mm','y_mm','potential_V','Ex_V_per_m','Ey_V_per_m','Ez_V_per_m'});outputDir=fileparts(outputCsv);if~isfolder(outputDir),mkdir(outputDir);end;writetable(samples,outputCsv);
    if particleEnabled
        assert(~isempty(particleEventsCsv)&&~isempty(particleSummaryJson)&&~isempty(particleRuntimeDir),'RF hybrid particle outputs are incomplete.');
        [events,particleSummary]=run_particle_diagnostic(model,comp,transport,g,particleTablePath,particleRuntimeDir,endHmax);eventDir=fileparts(particleEventsCsv);if~isfolder(eventDir),mkdir(eventDir);end;writetable(events,particleEventsCsv);summaryFile=fopen(particleSummaryJson,'w');assert(summaryFile>=0,'Could not create hybrid particle summary.');fprintf(summaryFile,'%s',jsonencode(particleSummary,'PrettyPrint',true));fclose(summaryFile);fprintf(fid,'PARTICLE_ROWS=%d\nPARTICLE_TRANSMITTED=%d\n',height(events),particleSummary.transmitted);
    end
    fprintf(fid,'SAMPLE_ROWS=%d\nPARTICLE_TRACKING=%d\nMODEL_SAVED=false\nSTATUS=PASS\n',height(samples),particleEnabled);
catch exception
    fprintf(fid,'STATUS=FAIL\nERROR=%s\n',getReport(exception,'extended','hyperlinks','off'));rethrow(exception)
end
clear cleanup

function [events,summary]=run_particle_diagnostic(model,comp,transport,g,particleTablePath,runtimeDir,endHmax)
ions=readmatrix(particleTablePath,'FileType','text','Delimiter',',');assert(size(ions,1)==transport.particle_count&&size(ions,2)==11,'Frozen N=100 ION table shape mismatch.');assert(all(abs(ions(:,2)-ions(1,2))<1e-12)&&all(abs(ions(:,3)-ions(1,3))<1e-12),'One particle run requires one mass and charge state.');if~isfolder(runtimeDir),mkdir(runtimeDir);end
cpt=comp.physics.create('cpt','ChargedParticleTracing','geom1');cpt.label('Hybrid-mesh paired N=100 diagnostic');cpt.selection.named('sel_vac');cpt.feature('pp1').set('mp',sprintf('%.17g[kg]',ions(1,2)*1.66053906660e-27));cpt.feature('pp1').set('Z',sprintf('%d',round(ions(1,3))));
for index=1:size(ions,1)
    speed=sqrt(2*ions(index,9)*1.602176634e-19/(ions(index,2)*1.66053906660e-27));az=deg2rad(ions(index,7));el=deg2rad(ions(index,8));vSim=[speed*cos(el)*cos(az),speed*cos(el)*sin(az),speed*sin(el)];releaseData=[ions(index,6),-ions(index,5),ions(index,4),-vSim(2),-vSim(3),vSim(1)];releasePath=fullfile(runtimeDir,sprintf('particle_%03d.txt',index));writematrix(releaseData,releasePath,'Delimiter','tab');rel=cpt.create(sprintf('rel%03d',index),'ReleaseFromDataFile',-1);rel.set('Filename',releasePath);rel.set('icolp','0');rel.set('VelocitySpecification','SpecifyVelocity');rel.set('InitialVelocity','FromFile');rel.set('icolv','3');rel.set('rt',sprintf('%.17g[us]',ions(index,1)));rel.importData();
end
scale=transport.rf_peak_V/100.0;frequency=transport.rf_frequency_Hz;phase=transport.rf_phase_rad;ef=cpt.create('ef1','ElectricForce',3);ef.selection.named('sel_vac');ef.set('E_src','userdef');ef.set('E',{sprintf('%.17g*es.Ex*sin(2*pi*%.17g[Hz]*t+%.17g)',scale,frequency,phase),sprintf('%.17g*es.Ey*sin(2*pi*%.17g[Hz]*t+%.17g)',scale,frequency,phase),sprintf('%.17g*es.Ez*sin(2*pi*%.17g[Hz]*t+%.17g)',scale,frequency,phase)});
std2=model.study.create('std2');time=std2.create('time1','Transient');dt=1/frequency/transport.rf_steps_per_period;tmax=(max(ions(:,1))+transport.maximum_particle_age_us)*1e-6;time.set('tlist',sprintf('range(0,%.17g,%.17g)',dt,tmax));time.setEntry('activate','es',false);time.setEntry('activate','cpt',true);for index=1:size(ions,1),cpt.feature(sprintf('rel%03d',index)).set('StudyStep','std2/time1');end;cpt.feature('pp1').set('StudyStep','std2/time1');sol2=model.sol.create('sol2');sol2.study('std2');sol2.createAutoSequence('std2');sol2.feature('v1').set('notsolmethod','sol');sol2.feature('v1').set('notsol','sol1');sol2.attach('std2');sol2.runAll;
pdset=model.result.dataset.create('pdset1','Particle');pdset.set('solution','sol2');pd=mphparticle(model,'dataset','pdset1');x=squeeze(pd.p(:,:,1));y=squeeze(pd.p(:,:,2));z=squeeze(pd.p(:,:,3));vx=squeeze(pd.v(:,:,1));vy=squeeze(pd.v(:,:,2));vz=squeeze(pd.v(:,:,3));assert(size(z,2)==size(ions,1),'Solved particle count mismatch.');radial=sqrt(x.^2+y.^2);handoffPlane=transport.nominal_handoff_z_mm-transport.handoff_evaluation_inset_mm;rows=cell(size(ions,1),19);transmitted=false(size(ions,1),1);
for index=1:size(ions,1)
    valid=find(isfinite(x(:,index))&isfinite(y(:,index))&isfinite(z(:,index))&isfinite(vx(:,index))&isfinite(vy(:,index))&isfinite(vz(:,index)));assert(~isempty(valid),'Particle %d has no finite state.',index);[state,found]=interpolate_plane(pd.t,x(:,index),y(:,index),z(:,index),vx(:,index),vy(:,index),vz(:,index),handoffPlane);event='terminal';status='lost';reason='electrode_or_boundary';
    if found,event='handoff';status='transmitted';reason='none';transmitted(index)=true;state.z_mm=transport.nominal_handoff_z_mm;else,last=valid(end);state=struct('t_s',pd.t(last),'x_mm',x(last,index),'y_mm',y(last,index),'z_mm',z(last,index),'vx_m_s',vx(last,index),'vy_m_s',vy(last,index),'vz_m_s',vz(last,index));if state.t_s-ions(index,1)*1e-6>=transport.maximum_particle_age_us*1e-6-dt,status='timeout';reason='timeout';elseif state.z_mm<0,reason='backward_escape';end,end
    speed2=state.vx_m_s^2+state.vy_m_s^2+state.vz_m_s^2;energy=0.5*ions(index,2)*1.66053906660e-27*speed2/1.602176634e-19;rodRadius=radial(:,index);rodRadius(z(:,index)<g.rod_z_min|z(:,index)>g.rod_z_max)=NaN;maxRod=max(rodRadius,[],'omitnan');maxAll=max(radial(:,index),[],'omitnan');rows(index,:)={index,event,status,reason,ions(index,1),state.t_s*1e6,(state.t_s-ions(index,1)*1e-6)*1e6,mod(2*pi*frequency*state.t_s+phase,2*pi),state.x_mm,state.y_mm,state.z_mm,state.vx_m_s,state.vy_m_s,state.vz_m_s,energy,hypot(state.x_mm,state.y_mm),atan2d(hypot(state.vx_m_s,state.vy_m_s),state.vz_m_s),maxRod,maxAll};
end
names={'particle_id','event','status','terminal_reason','birth_time_us','global_time_us','particle_age_us','rf_phase_rad','x_mm','y_mm','z_mm','vx_m_s','vy_m_s','vz_m_s','kinetic_energy_eV','radial_position_mm','divergence_angle_deg','max_rod_radius_mm','max_radius_mm'};events=cell2table(rows,'VariableNames',names);accepted=events(transmitted,:);summary=struct('schema_version',1,'role','rf_hybrid_mesh_n100_functional_arbitration','status','CHARACTERIZED','particles',height(events),'transmitted',sum(transmitted),'transmission',mean(transmitted),'end_core_hmax_mm',endHmax,'rf_peak_V',transport.rf_peak_V,'rf_frequency_Hz',frequency,'rf_steps_per_period',transport.rf_steps_per_period,'handoff_evaluation_z_mm',handoffPlane,'selection_allowed',false);
if~isempty(accepted),summary.mean_global_time_us=mean(accepted.global_time_us);summary.rms_radial_position_mm=sqrt(mean(accepted.radial_position_mm.^2));summary.rms_divergence_angle_deg=sqrt(mean(accepted.divergence_angle_deg.^2));summary.mean_kinetic_energy_eV=mean(accepted.kinetic_energy_eV);end
end

function [state,found]=interpolate_plane(time_s,x,y,z,vx,vy,vz,planeMm)
state=struct();found=false;valid=find(isfinite(x)&isfinite(y)&isfinite(z)&isfinite(vx)&isfinite(vy)&isfinite(vz));for index=2:numel(valid),a=valid(index-1);b=valid(index);if z(a)<planeMm&&z(b)>=planeMm&&z(b)>z(a),fraction=(planeMm-z(a))/(z(b)-z(a));lerp=@(left,right)left+fraction*(right-left);state=struct('t_s',lerp(time_s(a),time_s(b)),'x_mm',lerp(x(a),x(b)),'y_mm',lerp(y(a),y(b)),'z_mm',planeMm,'vx_m_s',lerp(vx(a),vx(b)),'vy_m_s',lerp(vy(a),vy(b)),'vz_m_s',lerp(vz(a),vz(b)));found=true;return,end,end
end

function add_cylinder(geom,tag,radius,height,zStart,selectionResult)
geom.feature.create(tag,'Cylinder');geom.feature(tag).set('r',sprintf('%.17g[mm]',radius));geom.feature(tag).set('h',sprintf('%.17g[mm]',height));geom.feature(tag).set('pos',{'0','0',sprintf('%.17g[mm]',zStart)});if selectionResult,geom.feature(tag).set('selresult','on');end
end
function add_annular_plate(geom,tag,outerRadius,holeRadius,zStart,thickness)
add_cylinder(geom,[tag 'O'],outerRadius,thickness,zStart,false);add_cylinder(geom,[tag 'H'],holeRadius,thickness,zStart,false);geom.feature.create(tag,'Difference');geom.feature(tag).selection('input').set({[tag 'O']});geom.feature(tag).selection('input2').set({[tag 'H']});geom.feature(tag).set('selresult','on');
end
function make_intersection(comp,tag,inputs)
comp.selection.create(tag,'Intersection');comp.selection(tag).set('entitydim',3);comp.selection(tag).set('input',inputs);
end
function add_size(parent,tag,geomTag,dimension,selectionTag,hmax,hmin)
feature=parent.feature.create(tag,'Size');feature.selection.geom(geomTag,dimension);feature.selection.named(selectionTag);feature.set('custom','on');feature.set('hmaxactive',true);feature.set('hmax',sprintf('%.17g[mm]',hmax));feature.set('hminactive',true);feature.set('hmin',sprintf('%.17g[mm]',hmin));
end
