param([ValidateSet(0.125,0.25,0.5)][double]$EndCoreHmaxMm=0.5,[switch]$ParticleDiagnostic,[string]$ParticleTablePath='',[string]$RunId='')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$repoRoot=(Resolve-Path (Join-Path $projectRoot '..\..')).Path;$workspaceRoot=Split-Path -Parent $repoRoot;$artifactRoot=Join-Path $workspaceRoot 'artifacts\projects\rf_quadrupole_collision_cooling';$python=Join-Path $repoRoot '.venv\Scripts\python.exe'
$contractSource=Join-Path $projectRoot 'config\rf_hybrid_mesh_candidate.json';$shieldContractSource=Join-Path $projectRoot 'config\rf_continuous_grounded_shield_candidate.json';& $python (Join-Path $projectRoot 'analysis\validate_rf_hybrid_mesh.py');if($LASTEXITCODE-ne 0){throw 'RF hybrid mesh contract failed.'};$shieldContractDocument=Get-Content -LiteralPath $shieldContractSource -Raw -Encoding UTF8|ConvertFrom-Json
$sourceMetadataPath=Join-Path $artifactRoot 'archive\20260719_212436__migration-snapshot__repo__pre-v2-layout\legacy-layout\runs\interface_sources\official_100amu_n100_20260718\particle_source_metadata.json';if($ParticleDiagnostic){if([string]::IsNullOrWhiteSpace($ParticleTablePath)){$ParticleTablePath=Join-Path (Split-Path -Parent $sourceMetadataPath) 'particles.ion'};$ParticleTablePath=[IO.Path]::GetFullPath($ParticleTablePath);foreach($path in @($ParticleTablePath,$sourceMetadataPath)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Frozen N=100 source evidence is missing: $path"}};if((Get-FileHash -LiteralPath $ParticleTablePath -Algorithm SHA256).Hash-ne$shieldContractDocument.n100_transport_screen.source_particle_table_sha256){throw 'Frozen N=100 particle table hash mismatch.'}}
if([string]::IsNullOrWhiteSpace($RunId)){$h=([string]$EndCoreHmaxMm).Replace('.','p');$RunId=(Get-Date -Format 'yyyyMMdd_HHmmss')+"__analysis__comsol__rf-hybrid-mesh__hend${h}"};& $python (Join-Path $repoRoot 'common\contracts\artifact_naming.py') run $RunId;if($LASTEXITCODE-ne 0){throw "Invalid run_id: $RunId"}
$runDir=Join-Path $artifactRoot "runs\$RunId";if(Test-Path -LiteralPath $runDir){throw "Run already exists: $runDir"};$inputDir=Join-Path $runDir 'inputs';$resultDir=Join-Path $runDir 'results';$logDir=Join-Path $runDir 'logs';New-Item -ItemType Directory -Force -Path $inputDir,$resultDir,$logDir|Out-Null
$task=Join-Path $inputDir 'build_rf_hybrid_mesh.m';$analysis=Join-Path $inputDir 'analyze_rf_continuous_shield_3d.py';$contract=Join-Path $inputDir 'rf_hybrid_mesh_candidate.json';$shieldContract=Join-Path $inputDir 'rf_continuous_grounded_shield_candidate.json';$resolved=Join-Path $inputDir 'resolved_geometry.json';$runner=Join-Path $inputDir 'run_rf_hybrid_mesh.ps1.txt';Copy-Item (Join-Path $PSScriptRoot 'build_rf_hybrid_mesh.m') $task;Copy-Item (Join-Path $projectRoot 'analysis\analyze_rf_continuous_shield_3d.py') $analysis;Copy-Item $contractSource $contract;Copy-Item $shieldContractSource $shieldContract;Copy-Item (Join-Path $projectRoot 'config\resolved_geometry.json') $resolved;Copy-Item $PSCommandPath $runner
$particleTable='';$sourceMetadata='';if($ParticleDiagnostic){$particleTable=Join-Path $inputDir 'particles.ion';$sourceMetadata=Join-Path $inputDir 'particle_source_metadata.json';Copy-Item $ParticleTablePath $particleTable;Copy-Item $sourceMetadataPath $sourceMetadata}
$fieldCsv=Join-Path $resultDir 'rf_hybrid_mesh_field_samples.csv';$particleEventsCsv=Join-Path $resultDir 'rf_hybrid_mesh_n100_events.csv';$particleSummaryJson=Join-Path $resultDir 'rf_hybrid_mesh_n100_metrics.json';$particleRuntimeDir=Join-Path $runDir 'runtime\particle_release_files';$report=Join-Path $logDir 'comsol_rf_hybrid_mesh.txt';$summary=Join-Path $runDir 'summary.json';$runConfig=Join-Path $runDir 'run_config.json';$manifestWriter=Join-Path $repoRoot 'common\contracts\write_run_manifest.py';$inputContract=[ordered]@{task=$task;analysis=$analysis;contract=$contract;shield_contract=$shieldContract;resolved_geometry=$resolved;runner=$runner};if($ParticleDiagnostic){$inputContract.particle_table=$particleTable;$inputContract.particle_source_metadata=$sourceMetadata};$runMode=if($ParticleDiagnostic){'rf_full_device_hybrid_mesh_n100_functional_arbitration'}else{'rf_full_device_hybrid_mesh_field'}
[ordered]@{schema_version=1;run_id=$RunId;project='rf_quadrupole_collision_cooling';mode=$runMode;project_root=$repoRoot;inputs=$inputContract;parameters=[ordered]@{end_core_hmax_mm=$EndCoreHmaxMm;uniform_core_radius_mm=8.0;uniform_core_hmax_mm=0.2;outer_hmax_mm=1.0;uniform_axial_layers=40;particle_tracking=[bool]$ParticleDiagnostic;particle_count=if($ParticleDiagnostic){100}else{0};model_saved=$false};formal_gate_passed=$false}|ConvertTo-Json -Depth 6|Set-Content $runConfig -Encoding UTF8
[ordered]@{schema_version=1;role='rf_hybrid_mesh_summary';status='interrupted'}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;& $python $manifestWriter --run-config $runConfig --status interrupted --software 'COMSOL 6.4' --software 'MATLAB R2025b' --software 'Python 3.11';if($LASTEXITCODE-ne 0){throw 'Initial manifest failed.'}
$names=@('RF_HYBRID_FIELD_CSV','RF_HYBRID_CONTRACT','RF_HYBRID_SHIELD_CONTRACT','RF_HYBRID_RESOLVED','RF_HYBRID_END_HMAX_MM','RF_HYBRID_PARTICLE_TABLE','RF_HYBRID_PARTICLE_EVENTS_CSV','RF_HYBRID_PARTICLE_SUMMARY_JSON','RF_HYBRID_PARTICLE_RUNTIME_DIR');$old=@{};foreach($name in $names){$old[$name]=[Environment]::GetEnvironmentVariable($name)}
try{try{$env:RF_HYBRID_FIELD_CSV=$fieldCsv;$env:RF_HYBRID_CONTRACT=$contract;$env:RF_HYBRID_SHIELD_CONTRACT=$shieldContract;$env:RF_HYBRID_RESOLVED=$resolved;$env:RF_HYBRID_END_HMAX_MM=[string]$EndCoreHmaxMm;if($ParticleDiagnostic){$env:RF_HYBRID_PARTICLE_TABLE=$particleTable;$env:RF_HYBRID_PARTICLE_EVENTS_CSV=$particleEventsCsv;$env:RF_HYBRID_PARTICLE_SUMMARY_JSON=$particleSummaryJson;$env:RF_HYBRID_PARTICLE_RUNTIME_DIR=$particleRuntimeDir}else{$env:RF_HYBRID_PARTICLE_TABLE=''};& (Join-Path $repoRoot 'common\comsol\run_comsol_r2025b.ps1') -TaskScript $task -ReportPath $report;if($LASTEXITCODE-ne 0){throw 'COMSOL RF hybrid mesh task failed.'}}finally{foreach($name in $names){[Environment]::SetEnvironmentVariable($name,$old[$name])}};& $python $analysis --input $fieldCsv --output-dir $resultDir;if($LASTEXITCODE-ne 0){throw 'RF hybrid field analysis failed.'}}catch{[ordered]@{schema_version=1;role='rf_hybrid_mesh_summary';status='failed';reason=$_.Exception.Message}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;& $python $manifestWriter --run-config $runConfig --status failed --software 'COMSOL 6.4' --software 'MATLAB R2025b' --software 'Python 3.11';throw}
[ordered]@{schema_version=1;role='rf_hybrid_mesh_summary';status='success';field_convergence_decision='UNRESOLVED';particle_diagnostic_completed=[bool]$ParticleDiagnostic;particle_acceptance_allowed=$false}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;$outputs=@($fieldCsv,(Join-Path $resultDir 'rf_continuous_shield_3d_harmonics.csv'),(Join-Path $resultDir 'rf_continuous_shield_3d_metrics.json'),$report,$summary);if($ParticleDiagnostic){$outputs+=@($particleEventsCsv,$particleSummaryJson)};$args=@($manifestWriter,'--run-config',$runConfig,'--status','success','--software','COMSOL 6.4','--software','MATLAB R2025b','--software','Python 3.11');foreach($output in $outputs){$args+=@('--output',$output)};& $python @args;if($LASTEXITCODE-ne 0){throw 'Final manifest failed.'};Write-Output "STATUS=PASS RUN_ID=$RunId FIELD_CONVERGENCE=UNRESOLVED PARTICLE_DIAGNOSTIC=$([bool]$ParticleDiagnostic)"
