param([ValidateSet(0.1,0.2)][double]$TransverseHmaxMm=0.2,[ValidateSet(20,40)][int]$AxialLayers=20,[ValidateSet('full','localized')][string]$MeshProfile='full',[ValidateSet(0.2,0.5,1.0)][double]$OuterHmaxMm=0.2,[ValidateSet(6.0,8.0,10.0)][double]$CoreRadiusMm=6.0,[string]$RunId='')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$repoRoot=(Resolve-Path (Join-Path $projectRoot '..\..')).Path;$workspaceRoot=Split-Path -Parent $repoRoot;$artifactRoot=Join-Path $workspaceRoot 'artifacts\projects\rf_quadrupole_collision_cooling';$python=Join-Path $repoRoot '.venv\Scripts\python.exe'
$contractSource=Join-Path $projectRoot 'config\rf_rod_region_swept_mesh_candidate.json';& $python (Join-Path $projectRoot 'analysis\validate_rf_rod_region_swept_mesh.py');if($LASTEXITCODE -ne 0){throw 'RF swept mesh contract failed.'}
if($MeshProfile -eq 'full' -and $OuterHmaxMm -ne $TransverseHmaxMm){throw 'Full profile requires OuterHmaxMm equal to TransverseHmaxMm.'};if($MeshProfile -eq 'localized' -and $OuterHmaxMm -notin @(1.0,0.5)){throw 'Localized profile requires a frozen outer hmax.'}
if([string]::IsNullOrWhiteSpace($RunId)){$h=([string]$TransverseHmaxMm).Replace('.','p');$ho=([string]$OuterHmaxMm).Replace('.','p');$rc=([string]$CoreRadiusMm).Replace('.','p');$RunId=(Get-Date -Format 'yyyyMMdd_HHmmss')+"__analysis__comsol__rf-rod-swept-mesh__${MeshProfile}-r${rc}-hxy${h}-hout${ho}-nz${AxialLayers}"}
& $python (Join-Path $repoRoot 'common\contracts\artifact_naming.py') run $RunId;if($LASTEXITCODE -ne 0){throw "Invalid run_id: $RunId"}
$runDir=Join-Path $artifactRoot "runs\$RunId";if(Test-Path -LiteralPath $runDir){throw "Run already exists: $runDir"};$inputDir=Join-Path $runDir 'inputs';$resultDir=Join-Path $runDir 'results';$logDir=Join-Path $runDir 'logs';New-Item -ItemType Directory -Force -Path $inputDir,$resultDir,$logDir|Out-Null
$task=Join-Path $inputDir 'build_rf_rod_region_swept_mesh.m';$analysis=Join-Path $inputDir 'analyze_rf_continuous_shield_3d.py';$contract=Join-Path $inputDir 'rf_rod_region_swept_mesh_candidate.json';$resolved=Join-Path $inputDir 'resolved_geometry.json';$runner=Join-Path $inputDir 'run_rf_rod_region_swept_mesh.ps1.txt'
Copy-Item (Join-Path $PSScriptRoot 'build_rf_rod_region_swept_mesh.m') $task;Copy-Item (Join-Path $projectRoot 'analysis\analyze_rf_continuous_shield_3d.py') $analysis;Copy-Item $contractSource $contract;Copy-Item (Join-Path $projectRoot 'config\resolved_geometry.json') $resolved;Copy-Item $PSCommandPath $runner
$fieldCsv=Join-Path $resultDir 'rf_rod_region_swept_field_samples.csv';$report=Join-Path $logDir 'comsol_rf_rod_region_swept_mesh.txt';$summary=Join-Path $runDir 'summary.json';$runConfig=Join-Path $runDir 'run_config.json';$manifestWriter=Join-Path $repoRoot 'common\contracts\write_run_manifest.py'
[ordered]@{schema_version=1;run_id=$RunId;project='rf_quadrupole_collision_cooling';mode='rf_uniform_rod_region_swept_mesh_field';project_root=$repoRoot;inputs=[ordered]@{task=$task;analysis=$analysis;contract=$contract;resolved_geometry=$resolved;runner=$runner};parameters=[ordered]@{mesh_profile=$MeshProfile;transverse_hmax_mm=$TransverseHmaxMm;outer_hmax_mm=$OuterHmaxMm;core_radius_mm=$CoreRadiusMm;axial_layers=$AxialLayers;particle_tracking=$false;model_saved=$false};formal_gate_passed=$false}|ConvertTo-Json -Depth 6|Set-Content $runConfig -Encoding UTF8
[ordered]@{schema_version=1;role='rf_rod_region_swept_mesh_summary';status='interrupted'}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;& $python $manifestWriter --run-config $runConfig --status interrupted --software 'COMSOL 6.4' --software 'MATLAB R2025b' --software 'Python 3.11';if($LASTEXITCODE -ne 0){throw 'Initial manifest failed.'}
$names=@('RF_SWEPT_FIELD_CSV','RF_SWEPT_CONTRACT','RF_SWEPT_RESOLVED','RF_SWEPT_TRANSVERSE_HMAX_MM','RF_SWEPT_AXIAL_LAYERS','RF_SWEPT_MESH_PROFILE','RF_SWEPT_OUTER_HMAX_MM','RF_SWEPT_CORE_RADIUS_MM');$old=@{};foreach($name in $names){$old[$name]=[Environment]::GetEnvironmentVariable($name)}
try{try{$env:RF_SWEPT_FIELD_CSV=$fieldCsv;$env:RF_SWEPT_CONTRACT=$contract;$env:RF_SWEPT_RESOLVED=$resolved;$env:RF_SWEPT_TRANSVERSE_HMAX_MM=[string]$TransverseHmaxMm;$env:RF_SWEPT_AXIAL_LAYERS=[string]$AxialLayers;$env:RF_SWEPT_MESH_PROFILE=$MeshProfile;$env:RF_SWEPT_OUTER_HMAX_MM=[string]$OuterHmaxMm;$env:RF_SWEPT_CORE_RADIUS_MM=[string]$CoreRadiusMm;& (Join-Path $repoRoot 'common\comsol\run_comsol_r2025b.ps1') -TaskScript $task -ReportPath $report;if($LASTEXITCODE -ne 0){throw 'COMSOL RF swept mesh task failed.'}}finally{foreach($name in $names){[Environment]::SetEnvironmentVariable($name,$old[$name])}};& $python $analysis --input $fieldCsv --output-dir $resultDir;if($LASTEXITCODE -ne 0){throw 'RF swept field analysis failed.'}}catch{[ordered]@{schema_version=1;role='rf_rod_region_swept_mesh_summary';status='failed';reason=$_.Exception.Message}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;& $python $manifestWriter --run-config $runConfig --status failed --software 'COMSOL 6.4' --software 'MATLAB R2025b' --software 'Python 3.11';throw}
[ordered]@{schema_version=1;role='rf_rod_region_swept_mesh_summary';status='success';physical_mesh_selected=$false;hybrid_integration_allowed=$false}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;$outputs=@($fieldCsv,(Join-Path $resultDir 'rf_continuous_shield_3d_harmonics.csv'),(Join-Path $resultDir 'rf_continuous_shield_3d_metrics.json'),$report,$summary);$args=@($manifestWriter,'--run-config',$runConfig,'--status','success','--software','COMSOL 6.4','--software','MATLAB R2025b','--software','Python 3.11');foreach($output in $outputs){$args+=@('--output',$output)};& $python @args;if($LASTEXITCODE -ne 0){throw 'Final manifest failed.'};Write-Output "STATUS=PASS RUN_ID=$RunId MESH_SELECTED=false"
