%RUN_CANDIDATE_CONTRACT_BUILD Build one isolated N=100 candidate MPH.
reportPath = getenv('COMSOL_BOOTSTRAP_REPORT');
contractPath = getenv('OATOF_CANDIDATE_CONTRACT_PATH');
modelPath = getenv('OATOF_CANDIDATE_MODEL_PATH');
runConfigPath = getenv('OATOF_CANDIDATE_RUN_CONFIG_PATH');
assert(~isempty(reportPath), 'COMSOL_BOOTSTRAP_REPORT is required.');
assert(isfile(contractPath), 'Candidate contract is missing: %s', contractPath);
assert(~isempty(modelPath), 'OATOF_CANDIDATE_MODEL_PATH is required.');
assert(isfile(runConfigPath), 'Candidate run config is missing: %s', runConfigPath);

testDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(testDir));
addpath(projectRoot, fullfile(projectRoot, 'comsol'));
contract = load_oatof_contract(contractPath);
runConfig = jsondecode(fileread(runConfigPath));
assert(isfield(runConfig, 'run_instance') && ...
    isfield(runConfig.run_instance, 'particle_source_seed') && ...
    isfield(runConfig.run_instance, 'particle_count'), ...
    'Candidate run_instance must declare seed and particle_count.');
assert(runConfig.run_instance.particle_count == 100, ...
    'Candidate structural workflow requires particle_count=100.');
assert(isfield(runConfig, 'inputs') && ...
    isfield(runConfig.inputs, 'candidate_particle_table'), ...
    'Candidate run config must bind candidate_particle_table.');
ionPath = runConfig.inputs.candidate_particle_table;
assert(isfile(ionPath), 'Candidate N=100 particle table is missing: %s', ionPath);

fid = fopen(reportPath, 'w');
assert(fid >= 0, 'Could not open report: %s', reportPath);
cleanup = onCleanup(@() fclose(fid));
try
    result = run_oatof_model( ...
        Label="ContractCandidate", ...
        ParticleCount=runConfig.run_instance.particle_count, ...
        FixedParticleTable=string(ionPath), ...
        OutputModelPath=string(modelPath), ContractPath=string(contractPath));
    assert(result.nP == 100 && result.nDet == 100, ...
        'Candidate detected only %d/%d particles.', result.nDet, result.nP);
    assert(numel(result.detectorStatus) == result.nP && ...
        all(result.detectorStatus == "detector_hit"), ...
        'Detector extraction did not classify each particle exactly once.');
    assert(isfile(modelPath), 'Candidate MPH was not saved.');
    import com.comsol.model.util.*
    model = ModelUtil.model('ModelOATOFRing');
    stage1Rings = round(model.param.evaluate('N_rings1'));
    stage2Rings = round(model.param.evaluate('N_rings2'));
    assert(stage1Rings == contract.rings.stage1_count && ...
        stage2Rings == contract.rings.stage2_count, ...
        'Parameterized ring counts differ from the candidate contract.');
    timeList = string(model.study('std2').feature('time1').getString('tlist'));
    requiredTimeTokens = ["cpt_dt_fine", "cpt_dt_drift", ...
        "cpt_t_refl_start", "cpt_t_refl_end", ...
        "cpt_t_detector_start", "cpt_t_detector_end"];
    assert(all(contains(timeList, requiredTimeTokens)), ...
        'Segmented particle time window is incomplete: %s', timeList);
    assert(strcmp(model.result.dataset('pdset1').getString('solution'), 'sol2'), ...
        'Particle dataset is not linked uniquely to sol2.');
    fprintf(fid, ['MODEL=%s\nCONTRACT=%s\nPARTICLES=%d\nDETECTED=%d\n' ...
        'DETECTOR_HIT_CLASSIFICATIONS=%d\nSTAGE1_RINGS=%d\n' ...
        'STAGE2_RINGS=%d\nTIME_WINDOW_TOKEN_COUNT=%d\n' ...
        'PARTICLE_DATASET=pdset1:sol2\nMEAN_TOF_US=%.12g\nSTATUS=PASS\n'], ...
        modelPath, contractPath, result.nP, result.nDet, ...
        sum(result.detectorStatus == "detector_hit"), stage1Rings, ...
        stage2Rings, numel(requiredTimeTokens), result.meanT*1e6);
catch exception
    fprintf(fid, 'STATUS=FAIL\nERROR=%s\n', getReport(exception, 'extended', 'hyperlinks', 'off'));
    rethrow(exception)
end
clear cleanup
