function transaction = oatof_assert_formal_write_authorized(destination, assetKind)
% Require an explicit exact-destination transaction before a Formal write.
transactionPath = string(getenv('OATOF_PROMOTION_TRANSACTION'));
assert(strlength(transactionPath)>0 && isfile(transactionPath), ...
    'oatofPromotion:MissingTransaction', ...
    'Formal writes require OATOF_PROMOTION_TRANSACTION.');
transaction = jsondecode(fileread(transactionPath));
assert(strcmp(transaction.role,'oa_tof_formal_promotion_transaction') && ...
    strcmp(transaction.project,'oa_tof') && strcmp(transaction.status,'authorized'), ...
    'oatofPromotion:InvalidTransaction', ...
    'Promotion transaction identity or status is invalid.');
assert(isfield(transaction.destinations,assetKind), ...
    'oatofPromotion:MissingDestination', ...
    'Promotion transaction does not authorize asset kind "%s".',assetKind);
expected = canonical_path(string(transaction.destinations.(assetKind)));
actual = canonical_path(string(destination));
assert(strcmpi(actual,expected), ...
    'oatofPromotion:DestinationMismatch', ...
    'Promotion destination differs from the authorized exact path.');
end

function value = canonical_path(path)
value = char(java.io.File(char(path)).getCanonicalPath());
end
