[CmdletBinding()]
param([Parameter(Mandatory)][string]$RunId,[string]$CampaignPath='',[string]$RuntimeCheckpointPath='',[string]$SimionExe='')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$repoRoot=(Resolve-Path (Join-Path $projectRoot '..\..')).Path;$workspaceRoot=(Resolve-Path (Join-Path $repoRoot '..')).Path
. (Join-Path $repoRoot 'common\require_powershell7.ps1');. (Join-Path $repoRoot 'common\contracts\run_artifact_support.ps1');. (Join-Path $repoRoot 'common\host_execution_lease.ps1');. (Join-Path $repoRoot 'common\simion\native_fast_adjust_runtime_support.ps1')
$python=Join-Path $repoRoot '.venv\Scripts\python.exe';if(-not$SimionExe){$SimionExe=Join-Path $env:ProgramFiles 'SIMION-2020\simion.exe'};foreach($item in @($python,$SimionExe)){if(-not(Test-Path -LiteralPath $item -PathType Leaf)){throw "Required executable is missing: $item"}}
$campaign=if($CampaignPath){(Resolve-Path -LiteralPath $CampaignPath).Path}else{Join-Path $projectRoot 'config\two_zone_component_focus_campaign.json'};$builder=Join-Path $projectRoot 'simion\build_component_focus_pa.lua';$artifactRoot=Join-Path $workspaceRoot 'artifacts';$cacheRoot=Join-Path $artifactRoot 'common\simion\pa_family_cache'
$package=New-RunPackage -Python $python -RepoRoot $repoRoot -ArtifactRoot (Join-Path $artifactRoot 'projects\orthogonal_accelerator') -RunId $RunId -Project orthogonal_accelerator -Mode component_focus_pa_build -Software @('SIMION 2020','Python 3.11') -RetentionContractEnabled -RetentionClass solver_review -RetentionReason 'One provider-owned closed-two-zone native controller for component focus; runtime flights use in-memory Fast Adjust.' -CapacityLedgerLifecycleEnabled -AdditionalDirectories @('simion') -UseShortExecutionPath
$lease=$null;$runtimeLease=$null;$buildAlias=$null;$runtimeAlias=$null;$capacity=$null;$retention=$null;$terminalized=$false;$temporary=$null;$verificationEvidence=$null;$runtimeCheckpoint=$null;$stage='preflight';$failureDetail=''
function Invoke-RootPython([string[]]$Arguments){Push-Location $repoRoot;try{&$python @Arguments;if($LASTEXITCODE-ne0){throw "Python stage failed: $($Arguments -join ' ')"}}finally{Pop-Location}}
try{
 $capacity=Enter-ArtifactWorkflowCapacitySession -Python $python -RepoRoot $repoRoot -ArtifactRoot $artifactRoot -RunDirectory $package.artifact_run_dir -CommittedNewBytes 0 -Owner "orthogonal-accelerator-focus-pa:$RunId"
 $stage='freeze_inputs';$frozenCampaign=Copy-VerifiedRunInput $campaign (Join-Path $package.input_dir 'campaign.json');$frozenPlanSource=Copy-VerifiedRunInput (Join-Path $projectRoot 'analysis\component_focus_pa_plan.py') (Join-Path $package.input_dir 'component_focus_pa_plan.py');$frozenCacheSource=Copy-VerifiedRunInput (Join-Path $projectRoot 'analysis\component_focus_pa_cache.py') (Join-Path $package.input_dir 'component_focus_pa_cache.py');$frozenBuilder=Copy-VerifiedRunInput $builder (Join-Path $package.input_dir 'build_component_focus_pa.lua');$frozenVerifier=Copy-VerifiedRunInput (Join-Path $projectRoot 'simion\verify_component_focus_pa.lua') (Join-Path $package.input_dir 'verify_component_focus_pa.lua');$frozenExporter=Copy-VerifiedRunInput (Join-Path $repoRoot 'common\simion\export_standalone_pa.lua') (Join-Path $package.input_dir 'export_standalone_pa.lua')
 $plan=Join-Path $package.result_dir 'component_focus_pa_plan.json';Invoke-RootPython @('-m','projects.orthogonal_accelerator.analysis.component_focus_pa_plan','--campaign',$frozenCampaign,'--output',$plan)
 $planDocument=Get-Content -Raw $plan|ConvertFrom-Json -Depth 30;$electrodeCount=[int]$planDocument.electrode_count
 $responseReceiptRecipe=Join-Path $package.input_dir 'standalone_response_receipt_recipe.json'
 Write-RunJson -Path $responseReceiptRecipe -Depth 12 -Value ([ordered]@{schema_version=1;receipt_name='orthogonal_accelerator_focus.standalone_responses.json';exporter_path=$frozenExporter;exports=@(1..$electrodeCount|ForEach-Object{[ordered]@{response_id=$_;source_name=('orthogonal_accelerator_focus.pa{0}'-f$_);standalone_name=('orthogonal_accelerator_focus.response{0}.pa'-f$_)}})})
 $probeText=@(Invoke-RootPython @('-m','projects.orthogonal_accelerator.analysis.component_focus_pa_cache','--action','probe','--cache-root',$cacheRoot,'--plan',$plan,'--builder',$frozenBuilder,'--simion-executable',$SimionExe);$null)|Out-String
 $probe=($probeText.Trim()|ConvertFrom-Json);$identity=Join-Path $package.result_dir 'component_focus_pa_cache_identity.json';$probe.identity|ConvertTo-Json -Depth 30|Set-Content $identity -Encoding utf8
 $domain=$probe.identity.grid_phase.stored_span_mm;$mesh=$probe.identity.mesh.mm_per_gu;[int64]$nodes=1;for($i=0;$i-lt3;$i++){$nodes*=[int64]([math]::Round([double]$domain[$i]/[double]$mesh[$i])+1)};$needsRuntime=[string]::IsNullOrWhiteSpace($RuntimeCheckpointPath);[int64]$required=$(if($probe.disposition-eq'hit'){0}else{3*($electrodeCount+2)*$nodes*8})+$(if($needsRuntime){($electrodeCount+1)*$nodes*8}else{0})
 $stage='capacity_startup';$updated=Update-ArtifactWorkflowCapacitySession -Python $python -RepoRoot $repoRoot -Session $capacity -ProtectedCacheKeys @([string]$probe.cache_key) -RemainingCommittedNewBytes $required;$capacity=$updated.session;Write-RunJson -Path (Join-Path $package.result_dir 'artifact_capacity_gate_startup.json') -Depth 14 -Value $updated
 # Capacity-ledger terminal publication requires this immutable retention
 # receipt. Create it while this run contains only frozen light inputs, before
 # any private native PA or cache publication exists.
 $stage='retention_prebuild';$retention=Apply-RunArtifactRetention -Python $python -RepoRoot $repoRoot -RunConfig $package.run_config
 if($probe.disposition-eq'hit'){$publication=$probe}else{
   if($probe.disposition-ne'miss'){throw "Focus-controller cache is not usable: $($probe.disposition)"}
   $stage='transaction_start'
   $transactionText=@(Invoke-RootPython @('-m','projects.orthogonal_accelerator.analysis.component_focus_pa_cache','--action','advance-transaction','--cache-root',$cacheRoot,'--plan',$plan,'--builder',$frozenBuilder,'--simion-executable',$SimionExe,'--owner',$capacity.owner,'--producer-run-config',$package.run_config,'--response-receipt',$responseReceiptRecipe);$null)|Out-String
   $transaction=($transactionText.Trim()|ConvertFrom-Json)
   if($transaction.action_required-ne'build'){throw "Focus PA transaction cannot build: $($transaction.action_required)"}
   $stage='native_build';$temporary=[string]$transaction.scratch_directory;$gem=Join-Path $temporary 'focus.gem';Set-Content -LiteralPath $gem -Value ([string]$planDocument.gem) -Encoding ascii
   $raw=Join-Path $transaction.build_directory 'orthogonal_accelerator_focus.pa#';$lease=Enter-HostExecutionLease -Role SIMION -Stage pa_refine -RunId $RunId
   Push-Location $temporary;try{&$SimionExe --nogui --noprompt lua $frozenBuilder $gem $raw $electrodeCount 2>&1|Tee-Object (Join-Path $package.log_dir 'build_component_focus_pa.log');if($LASTEXITCODE-ne0){throw 'Native focus controller build failed'}}finally{Pop-Location}
   $stage='export_standalone_responses';$buildAlias=New-RunExecutionAlias -TargetDirectory ([string]$transaction.build_directory)
   foreach($responseId in 1..$electrodeCount){
     $source=Join-Path ([string]$buildAlias.execution_alias) ('orthogonal_accelerator_focus.pa{0}'-f$responseId)
     $standalone=Join-Path ([string]$buildAlias.execution_alias) ('orthogonal_accelerator_focus.response{0}.pa'-f$responseId)
     &$SimionExe --nogui --noprompt lua $frozenExporter $source $standalone 2>&1|Tee-Object -Append (Join-Path $package.log_dir 'export_component_focus_responses.log')
     if($LASTEXITCODE-ne0){throw "Standalone focus response export failed for ID $responseId"}
   }
   Remove-RunExecutionAlias -ExecutionAlias ([string]$buildAlias.execution_alias) -TargetDirectory ([string]$buildAlias.target_directory);$buildAlias=$null
   Exit-HostExecutionLease -Lease $lease -Outcome success -RunId $RunId;$lease=$null
   $stage='seal_and_verify';$sealedText=@(Invoke-RootPython @('-m','projects.orthogonal_accelerator.analysis.component_focus_pa_cache','--action','advance-transaction','--cache-root',$cacheRoot,'--plan',$plan,'--builder',$frozenBuilder,'--simion-executable',$SimionExe,'--owner',$capacity.owner,'--response-receipt',$responseReceiptRecipe);$null)|Out-String;$sealed=($sealedText.Trim()|ConvertFrom-Json)
   if($sealed.action_required-ne'verify'){throw "Focus PA transaction cannot verify: $($sealed.action_required)"}
   $grid=@();for($i=0;$i-lt3;$i++){$grid+=([int]([math]::Round([double]$domain[$i]/[double]$mesh[$i]))+1)};$verificationOutput=Join-Path $package.log_dir 'verify_component_focus_pa.log';&$SimionExe --nogui --noprompt lua $frozenVerifier $raw $electrodeCount $grid[0] $grid[1] $grid[2] 2>&1|Tee-Object $verificationOutput;if($LASTEXITCODE-ne0){throw 'Native focus controller verification failed'}
   $verificationEvidence=Join-Path $package.result_dir 'component_focus_pa_verification.json';[ordered]@{schema_version=1;role='simion_pa_family_verification';status='pass';cache_key=[string]$sealed.cache_key;inventory_sha256=[string]$sealed.inventory_sha256;solver_release='SIMION 2020';verifier_path=(Resolve-Path $frozenVerifier).Path;verifier_sha256=(Get-FileHash $frozenVerifier -Algorithm SHA256).Hash;verification_output_path=(Resolve-Path $verificationOutput).Path;verification_output_sha256=(Get-FileHash $verificationOutput -Algorithm SHA256).Hash}|ConvertTo-Json -Depth 8|Set-Content $verificationEvidence -Encoding utf8
   $stage='publish';$publicationText=@(Invoke-RootPython @('-m','projects.orthogonal_accelerator.analysis.component_focus_pa_cache','--action','advance-transaction','--cache-root',$cacheRoot,'--plan',$plan,'--builder',$frozenBuilder,'--simion-executable',$SimionExe,'--owner',$capacity.owner,'--verification-evidence',$verificationEvidence,'--response-receipt',$responseReceiptRecipe);$null)|Out-String;$publication=($publicationText.Trim()|ConvertFrom-Json);if($publication.action_required-ne'complete'){throw "Focus PA transaction did not complete publication: $($publication.action_required)"}
 }
 $stage='prepare_shared_private_runtime'
 $ownsRuntime=$needsRuntime
 if($RuntimeCheckpointPath){
   $runtimeCheckpoint=(Resolve-Path -LiteralPath $RuntimeCheckpointPath).Path
   $runtimeOwnerRun=Split-Path -Parent (Split-Path -Parent $runtimeCheckpoint)
   $savedRuntime=Get-Content -LiteralPath $runtimeCheckpoint -Raw -Encoding UTF8|ConvertFrom-Json -Depth 30
   $runtimeDirectory=(Resolve-Path -LiteralPath ([string]$savedRuntime.directory)).Path
 }else{
   $runtimeOwnerRun=$package.artifact_run_dir
   $runtimeDirectory=Join-Path $runtimeOwnerRun 'runtime\accelerator_family'
   $runtimeCheckpoint=Join-Path $runtimeOwnerRun 'results\accelerator_runtime_checkpoint.json'
   New-Item -ItemType Directory -Path $runtimeDirectory -Force|Out-Null;$runtimeAlias=New-RunExecutionAlias -TargetDirectory $runtimeDirectory;$runtimeLease=Enter-HostResourceStage -Role SIMION -Stage prepare -RunId $RunId -Budget (Get-HostResourceBudget -Role SIMION -Stage prepare)
   try{$runtime=New-NativeFastAdjustRuntimeFamily -GenerationDirectory ([string]$publication.generation_directory) -ExpectedCacheKey ([string]$publication.cache_key) -ExpectedGenerationSha256 ([string]$publication.generation_sha256) -ReceiptName 'orthogonal_accelerator_focus.standalone_responses.json' -RawName 'orthogonal_accelerator_focus.pa#' -FamilyPrefix 'orthogonal_accelerator_focus' -ExpectedResponseIds @(1..$electrodeCount) -DestinationDirectory ([string]$runtimeAlias.execution_alias) -Python $python -RepoRoot $repoRoot -SimionExe $SimionExe -ResourceLease $runtimeLease -RunId $RunId -ReceiptRole 'orthogonal_accelerator_shared_private_native_family';$runtimeLease=$runtime.resource_lease}finally{if($runtimeLease){Exit-HostResourceStage -Lease $runtimeLease;$runtimeLease=$null}}
   $members=@();foreach($index in 0..$electrodeCount){$member=Get-Item -LiteralPath (Join-Path $runtimeDirectory ('orthogonal_accelerator_focus.pa'+$index));$member.IsReadOnly=$true;$members+=@([ordered]@{name=$member.Name;bytes=[int64]$member.Length})};Write-RunJson -Path $runtimeCheckpoint -Depth 20 -Value ([ordered]@{schema_version=1;role='orthogonal_accelerator_shared_runtime_checkpoint';status='prepared';cache_key=[string]$publication.cache_key;generation_sha256=[string]$publication.generation_sha256;directory=$runtimeDirectory;members=$members;controller_refine='solutions={0}';response_refine_performed=$false;published_native_members_opened=$false})
 }
 $runtimeState=Get-Content -LiteralPath $runtimeCheckpoint -Raw -Encoding UTF8|ConvertFrom-Json -Depth 30;$expectedRuntimeNames=@(0..$electrodeCount|ForEach-Object{'orthogonal_accelerator_focus.pa'+$_});if([string]$runtimeState.role-ne'orthogonal_accelerator_shared_runtime_checkpoint'-or[string]$runtimeState.status-ne'prepared'-or[string]$runtimeState.cache_key-ne[string]$publication.cache_key-or[string]$runtimeState.generation_sha256-ne[string]$publication.generation_sha256-or[IO.Path]::GetFullPath([string]$runtimeState.directory)-ne[IO.Path]::GetFullPath($runtimeDirectory)-or@($runtimeState.members).Count-ne$expectedRuntimeNames.Count-or@(Compare-Object @($runtimeState.members.name) $expectedRuntimeNames).Count-ne0){throw 'Shared accelerator runtime checkpoint field identity or inventory differs.'};foreach($record in @($runtimeState.members)){$member=Get-Item -LiteralPath (Join-Path $runtimeDirectory ([string]$record.name));if(-not$member.IsReadOnly-or[int64]$member.Length-ne[int64]$record.bytes){throw 'Shared accelerator runtime member protection differs.'}}
 $publication|Add-Member -NotePropertyName runtime_checkpoint_path -NotePropertyValue $runtimeCheckpoint -Force;$publication|Add-Member -NotePropertyName runtime_controller_path -NotePropertyValue (Join-Path $runtimeDirectory 'orthogonal_accelerator_focus.pa0') -Force
 $result=Join-Path $package.result_dir 'component_focus_pa_result.json';$publication|ConvertTo-Json -Depth 30|Set-Content $result -Encoding utf8;$summary=[ordered]@{schema_version=1;role='orthogonal_accelerator_component_focus_pa';status='success';qualification='native_controller_plus_standalone_responses__focus_flight_pending';cache_key=$publication.cache_key;generation_sha256=$publication.generation_sha256;generation_directory=$publication.generation_directory;runtime_checkpoint_path=$runtimeCheckpoint;native_family_members=@('orthogonal_accelerator_focus.pa#')+@(0..$electrodeCount|ForEach-Object{"orthogonal_accelerator_focus.pa$_"});standalone_response_members=@(1..$electrodeCount|ForEach-Object{"orthogonal_accelerator_focus.response$_.pa"});standalone_response_receipt='orthogonal_accelerator_focus.standalone_responses.json';cache_policy='published_native_family_provenance__runtime_opens_only_manifest_bound_standalone_responses'};Write-RunJson -Path $package.summary -Depth 16 -Value $summary
 $outputs=@($package.summary,$result,$plan,$identity,$retention,(Join-Path $package.result_dir 'artifact_capacity_gate_startup.json'));if($ownsRuntime){$outputs+=$runtimeCheckpoint};$buildLog=Join-Path $package.log_dir 'build_component_focus_pa.log';$verifyLog=Join-Path $package.log_dir 'verify_component_focus_pa.log';if(Test-Path -LiteralPath $buildLog -PathType Leaf){$outputs+=@($buildLog)};if(Test-Path -LiteralPath $verifyLog -PathType Leaf){$outputs+=@($verifyLog)};if($verificationEvidence -and(Test-Path -LiteralPath $verificationEvidence -PathType Leaf)){$outputs+=@($verificationEvidence)}
 if($ownsRuntime){
   Write-VerifiedRunManifest -Python $python -RepoRoot $repoRoot -RunConfig $package.run_config -Status checkpoint -Software @('SIMION 2020','Python 3.11') -Outputs $outputs|Out-Host
 }else{
   $stage='capacity_terminal';$terminal=Update-ArtifactWorkflowCapacitySession -Python $python -RepoRoot $repoRoot -Session $capacity -RemainingCommittedNewBytes 0;$capacity=$terminal.session;$terminalPath=Join-Path $package.result_dir 'artifact_capacity_gate_terminal.json';Write-RunJson -Path $terminalPath -Depth 14 -Value $terminal;$outputs+=$terminalPath
   Write-VerifiedRunManifest -Python $python -RepoRoot $repoRoot -RunConfig $package.run_config -Status success -Software @('SIMION 2020','Python 3.11') -Outputs $outputs|Out-Host
 }
 $terminalized=$true
}catch{$failureDetail=$_.Exception.Message;throw
}finally{if(-not$terminalized){$reason="Focus PA build failed at $stage.";if(-not[string]::IsNullOrWhiteSpace($failureDetail)){$reason+=" $failureDetail"};Complete-FailedRun -Python $python -RepoRoot $repoRoot -RunConfig $package.run_config -Summary $package.summary -SummaryRole orthogonal_accelerator_component_focus_pa -Reason $reason -Software @('SIMION 2020','Python 3.11') -Status failed};if($buildAlias){Remove-RunExecutionAlias -ExecutionAlias ([string]$buildAlias.execution_alias) -TargetDirectory ([string]$buildAlias.target_directory)};if($runtimeAlias){Remove-RunExecutionAlias -ExecutionAlias ([string]$runtimeAlias.execution_alias) -TargetDirectory ([string]$runtimeAlias.target_directory)};if($runtimeLease){Exit-HostResourceStage -Lease $runtimeLease};if($lease){Exit-HostExecutionLease -Lease $lease -Outcome $(if($terminalized){'success'}else{'failed'}) -RunId $RunId};if($capacity){$null=Exit-ArtifactWorkflowCapacitySession -Python $python -RepoRoot $repoRoot -Session $capacity};if($temporary -and(Test-Path $temporary)){Remove-Item -LiteralPath $temporary -Recurse -Force};Remove-RunPackageExecutionAlias -Package $package}
