[CmdletBinding()]
param([Parameter(Mandatory)][string]$RunId,[Parameter(Mandatory)][string]$PABuildRunPath,[Parameter(Mandatory)][string]$CampaignPath,[Parameter(Mandatory)][string]$ReleaseSpecPath,[ValidateSet('native','zone1_ideal','zone2_ideal','full_ideal')][string]$FieldMode='native',[string]$SimionExe='')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$repoRoot=(Resolve-Path (Join-Path $projectRoot '..\..')).Path;$workspaceRoot=(Resolve-Path (Join-Path $repoRoot '..')).Path
. (Join-Path $repoRoot 'common\require_powershell7.ps1');. (Join-Path $repoRoot 'common\contracts\run_artifact_support.ps1');. (Join-Path $repoRoot 'common\host_execution_lease.ps1')
$python=Join-Path $repoRoot '.venv\Scripts\python.exe';if(-not$SimionExe){$SimionExe=Join-Path $env:ProgramFiles 'SIMION-2020\simion.exe'};if(-not(Test-Path $SimionExe)){throw 'SIMION executable is missing'}
$previousPythonPath=$env:PYTHONPATH;$env:PYTHONPATH=$repoRoot
$family=(Resolve-Path $PABuildRunPath).Path;& $python (Join-Path $repoRoot 'common\contracts\verify_run_manifest.py') (Join-Path $family 'run_manifest.json') --require-status success --require-project orthogonal_accelerator --require-mode component_focus_pa_build;if($LASTEXITCODE-ne0){throw 'Provider focus-PA manifest verification failed'}
$result=Get-Content -Raw (Join-Path $family 'results\component_focus_pa_result.json')|ConvertFrom-Json;if(@('published','hit')-notcontains$result.disposition){throw 'Focus PA is not a published cache generation'}
$plan=Join-Path $family 'results\component_focus_pa_plan.json';if(-not(Test-Path $plan)){throw 'Provider focus PA plan is missing'};$generation=(Resolve-Path $result.generation_directory).Path;$manifest=Get-Content -Raw (Join-Path $generation 'cache_manifest.json')|ConvertFrom-Json;$nativeNames=@('orthogonal_accelerator_focus.pa#')+@(0..9|ForEach-Object{"orthogonal_accelerator_focus.pa$_"});if((@($manifest.files|ForEach-Object{$_.name})-join ',')-ne($nativeNames-join ',')){throw 'Published provider cache inventory is not the exact native Fast Adjust family'};$controller=Join-Path $generation 'orthogonal_accelerator_focus.pa0';if(-not(Test-Path $controller)){throw 'Published provider cache lacks native PA0 controller'}
$campaign=(Resolve-Path -LiteralPath $CampaignPath).Path;$package=New-RunPackage -Python $python -RepoRoot $repoRoot -ArtifactRoot (Join-Path $workspaceRoot 'artifacts\projects\orthogonal_accelerator') -RunId $RunId -Project orthogonal_accelerator -Mode component_focus_flight -Software @('SIMION 2020','Python 3.11') -RetentionContractEnabled -RetentionClass solver_review -RetentionReason 'Independent closed-two-zone component focus flight.' -AdditionalDirectories @('simion')
$lease=$null;$done=$false;$failureDetail='';try{$lease=Enter-HostExecutionLease -Role SIMION -Stage flight -RunId $RunId;$run=$package.run_dir;$inputs=$package.input_dir;$solver=Join-Path $run 'simion';$results=$package.result_dir;$logs=$package.log_dir
 $campaignTemplate=Join-Path $inputs 'campaign_template.json';$runCampaign=Join-Path $inputs 'campaign.json';Copy-VerifiedRunInput $campaign $campaignTemplate|Out-Null;Copy-VerifiedRunInput $plan (Join-Path $inputs 'component_focus_pa_plan.json')|Out-Null;Copy-VerifiedRunInput (Join-Path $projectRoot 'analysis\component_focus_simion_source.py') (Join-Path $solver 'component_focus_simion_source.py')|Out-Null;Copy-VerifiedRunInput (Join-Path $projectRoot 'analysis\component_focus_analysis.py') (Join-Path $solver 'component_focus_analysis.py')|Out-Null;Copy-VerifiedRunInput (Join-Path $projectRoot 'simion\component_focus.lua') (Join-Path $solver 'component_focus.lua')|Out-Null;Copy-VerifiedRunInput (Join-Path $projectRoot 'simion\build_component_focus_iob.lua') (Join-Path $solver 'build_component_focus_iob.lua')|Out-Null
 $releaseSpec=Join-Path $inputs 'release_spec.json';$c=Get-Content -Raw $campaignTemplate|ConvertFrom-Json;Copy-VerifiedRunInput (Resolve-Path -LiteralPath $ReleaseSpecPath).Path $releaseSpec|Out-Null;$c.release_spec=(Get-Content -Raw $releaseSpec|ConvertFrom-Json);$c|ConvertTo-Json -Depth 12|Set-Content $runCampaign -Encoding utf8;$p=Get-Content -Raw (Join-Path $inputs 'component_focus_pa_plan.json')|ConvertFrom-Json;$paSpan=@($p.numerical_domain.span_mm);if($paSpan.Count-ne3){throw 'Provider PA span metadata is invalid'};for($i=0;$i-lt3;$i++){if([double]$paSpan[$i]-ne[double]$manifest.identity.grid_phase.pa_span_mm[$i]){throw 'Published PA span differs from provider plan'}};$resolvedProjection=$c.simion_projection.PSObject.Copy();$resolvedProjection.local_pa_span_mm=@($paSpan);$resolvedProjection.local_exit_z_mm=[double]$p.numerical_domain.local_exit_z_mm;$projectionPath=Join-Path $inputs 'resolved_projection.json';$resolvedProjection|ConvertTo-Json -Depth 12|Set-Content $projectionPath -Encoding utf8;$originX=[double]$p.numerical_domain.iob_origin_mm[0];$originY=[double]$p.numerical_domain.iob_origin_mm[1]+[double]$c.operating_point.instance_center_y_mm;$originZ=[double]$p.numerical_domain.iob_origin_mm[2];$release=Join-Path $inputs 'release.csv';$releaseReceipt=Join-Path $inputs 'release_receipt.json';&$python -m common.ion_release.cylinder --materialize $releaseSpec --state-table $release --receipt $releaseReceipt;if($LASTEXITCODE-ne0){throw 'Common ion release failed'}
 $fly=Join-Path $solver 'component_focus_input.fly2';$sourceStates=Join-Path $solver 'component_focus.source_states.lua';$sourceReceipt=Join-Path $results 'source_projection.json';&$python -m projects.orthogonal_accelerator.analysis.component_focus_simion_source --release-receipt $releaseReceipt --campaign $runCampaign --provider-plan (Join-Path $inputs 'component_focus_pa_plan.json') --resolved-projection $projectionPath --fly2 $fly --source-states $sourceStates --receipt $sourceReceipt;if($LASTEXITCODE-ne0){throw 'SIMION source projection failed'}
 $op=Join-Path $solver 'component_focus.operating_point.lua';$volts=($c.operating_point.electrode_voltages_v|ForEach-Object{[string]$_}) -join ',';@("return { voltages={ $volts }, field_mode='$FieldMode', trajectory_quality=$($c.numerics.trajectory_quality), maximum_step_us=$($c.numerics.maximum_step_us), particle_count=$($c.release_spec.particle_count), focus_plane_tolerance_mm=$($c.acceptance.focus_plane_tolerance_mm), local_exit_z_mm=$($p.numerical_domain.local_exit_z_mm), focus_plane_offset_from_exit_mm=$($c.operating_point.focus_plane_offset_from_exit_mm), focus_plane_local_z_mm=$($p.numerical_domain.focus_plane_local_z_mm), grid1_local_z_mm=$($p.layout.local_exit_z_mm + $p.layout.gap_2_mm), repeller_local_z_mm=$($p.layout.local_repeller_z_mm) }")|Set-Content $op -Encoding ascii
 $seed=Join-Path $repoRoot 'common\simion\assets\iob_instance_seeds\1_instance_seed.iob';$iob=Join-Path $solver 'component_focus.iob';&$SimionExe --nogui --noprompt lua (Join-Path $solver 'build_component_focus_iob.lua') -- $seed $controller $iob (Join-Path $solver 'component_focus.lua') $fly $originX $originY $originZ 2>&1|Tee-Object (Join-Path $logs 'iob_build.log');if($LASTEXITCODE-ne0){throw 'IOB build failed'}
 Push-Location $solver;try{&$SimionExe --nogui --noprompt fly --trajectory-quality $($c.numerics.trajectory_quality) --particles $fly --programs 1 --retain-trajectories 0 $iob 2>&1|Tee-Object (Join-Path $logs 'focus.log');if($LASTEXITCODE-ne0){throw 'SIMION flight failed'}}finally{Pop-Location}
 $events=Join-Path $solver 'component_focus.events.csv';if(-not(Test-Path -LiteralPath $events) -or (Get-Item -LiteralPath $events).Length -le 0){throw 'SIMION did not produce component-focus event CSV'}
 $analysis=Join-Path $results 'focus_analysis.json';&$python -m projects.orthogonal_accelerator.analysis.component_focus_analysis --events $events --release-receipt $releaseReceipt --campaign $runCampaign --output $analysis;$analysisExit=$LASTEXITCODE;if($analysisExit-ne0-and-not(Test-Path -LiteralPath $analysis)){throw 'Component focus analysis did not produce evidence'};$analysisResult=Get-Content -Raw $analysis|ConvertFrom-Json;if($analysisResult.status-notin@('candidate_complete','candidate_incomplete')){throw 'Component focus analysis status is invalid'}
 $summary=Join-Path $run 'summary.json';@{schema_version=1;role='orthogonal_accelerator_component_focus';status=[string]$analysisResult.status;qualification='candidate_prototype_numeric_component_focus_only';cache_key=$result.cache_key;generation_sha256=$result.generation_sha256;pa_build_run_manifest_sha256=(Get-FileHash (Join-Path $family 'run_manifest.json') -Algorithm SHA256).Hash;cache_manifest_sha256=(Get-FileHash (Join-Path $generation 'cache_manifest.json') -Algorithm SHA256).Hash;controller_sha256=(Get-FileHash $controller -Algorithm SHA256).Hash;pa_cache_policy='published_read_only__runtime_fast_adjust__no_copy_refine_or_rebuild'}|ConvertTo-Json|Set-Content $summary -Encoding utf8;Write-VerifiedRunManifest -Python $python -RepoRoot $repoRoot -RunConfig $package.run_config -Status success -Software @('SIMION 2020','Python 3.11') -Outputs @($summary,$analysis,$sourceReceipt,$releaseReceipt,$fly,$sourceStates,$iob,$events,(Join-Path $logs 'focus.log'));$done=$true
}catch{$failureDetail=$_.Exception.Message;throw
}finally{if(-not$done){$reason='Focus runner failed.';if(-not[string]::IsNullOrWhiteSpace($failureDetail)){$reason+=" $failureDetail"};Complete-FailedRun -Python $python -RepoRoot $repoRoot -RunConfig $package.run_config -Summary $package.summary -SummaryRole orthogonal_accelerator_component_focus -Reason $reason -Software @('SIMION 2020','Python 3.11') -Status failed};if($lease){Exit-HostExecutionLease -Lease $lease -Outcome $(if($done){'success'}else{'failed'}) -RunId $RunId};Remove-RunPackageExecutionAlias -Package $package;$env:PYTHONPATH=$previousPythonPath}
