function contract = load_oatof_contract(contractPath)
%LOAD_OATOF_CONTRACT Load the generated oa-TOF resolved machine contract.
% Humans edit baseline.json and modes/formal.json; programs consume only
% resolved_geometry.json so every language sees the same derived values.

projectRoot = fileparts(mfilename('fullpath'));
if nargin < 1 || strlength(string(contractPath)) == 0
    contractPath = fullfile(projectRoot, 'config', 'resolved_geometry.json');
end
contractPath = char(contractPath);
assert(isfile(contractPath), 'oatof:MissingResolvedContract', ...
    ['Missing resolved contract "%s". Generate the formal contract with ' ...
     'analysis/resolve_geometry.py --write or compile an isolated candidate.'], ...
    contractPath);
contract = jsondecode(fileread(contractPath));
assert(contract.schema_version == 1 && ...
    strcmp(contract.role, 'oa_tof_resolved_contract_do_not_edit'), ...
    'oatof:ResolvedSchema', 'Unsupported resolved contract schema.');

g = contract.geometry_mm;
a = contract.geometry_derivation.accelerator;
s = contract.particle_source;
must_be_near(g.accelerator_grid1_z, g.accelerator_repeller_z + a.d1_mm, ...
    'accelerator grid1 z');
must_be_near(g.accelerator_grid2_z, g.accelerator_grid1_z + a.d2_mm, ...
    'accelerator grid2 z');
must_be_near(g.accelerator_focus_z, ...
    g.accelerator_grid2_z + a.focus_drift_after_grid2_mm, ...
    'accelerator focus z');
must_be_near(g.detector_z, g.accelerator_focus_z, 'detector/focus z');
must_be_near(g.L_accel, a.d1_mm + a.d2_mm, 'accelerator total length');
must_be_near(g.L_reflectron, g.L_stage1 + g.L_stage2, ...
    'reflectron total length');
must_be_near(s.center_x_mm, ...
    contract.coordinate_convention.accelerator_axis_x, 'source x/axis');
if strcmp(s.center_z_rule, ...
        'accelerator_repeller_z + accelerator_stage1_length_mm/2')
    expectedSourceZ = g.accelerator_repeller_z + a.d1_mm/2;
    if abs(double(s.center_z_mm)-double(expectedSourceZ)) > 1e-10 && ...
            isfield(a, 'finite_interval_theory')
        theory = a.finite_interval_theory;
        finiteIntervalSourceZ = theory.canonical_repeller_z_mm + ...
            theory.source_center_mm;
        if abs(double(s.center_z_mm)-double(finiteIntervalSourceZ)) <= 1e-10
            expectedSourceZ = finiteIntervalSourceZ;
        end
    end
elseif strcmp(s.center_z_rule, ...
        ['geometry_derivation.accelerator.finite_interval_theory.' ...
         'canonical_repeller_z_mm + source_center_mm'])
    theory = a.finite_interval_theory;
    expectedSourceZ = theory.canonical_repeller_z_mm + theory.source_center_mm;
else
    error('oatof:SourceCenterRule', ...
        'Unsupported particle_source.center_z_rule: %s', s.center_z_rule);
end
must_be_near(s.center_z_mm, expectedSourceZ, 'source center z');
end

function must_be_near(actual, expected, label)
assert(abs(double(actual) - double(expected)) <= 1e-10, ...
    'oatof:ResolvedDerivation', ...
    '%s is inconsistent: actual=%.17g expected=%.17g', ...
    label, actual, expected);
end
