param(
    [Parameter(Mandatory)][ValidateSet('transport_no_collision','transport_interface_readiness')][string]$Mode,
    [Parameter(Mandatory)][string]$ComsolRunId,
    [Parameter(Mandatory)][string]$SimionRunId,
    [string]$RunId='',[string]$PythonExe='',[string]$ParticleTablePath='',
    [double]$FrequencyHz=[double]::NaN,[double]$PhaseRad=0.0
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$projectRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$repoRoot=Split-Path -Parent (Split-Path -Parent $projectRoot)
$workspaceRoot=Split-Path -Parent $repoRoot
$artifactRoot=Join-Path $workspaceRoot 'artifacts\projects\rf_quadrupole_ion_optics'
$python=if($PythonExe){[IO.Path]::GetFullPath($PythonExe)}else{Join-Path $repoRoot '.venv\Scripts\python.exe'}
. (Join-Path $repoRoot 'common\contracts\run_artifact_support.ps1')
. (Join-Path $projectRoot 'runtime\cross_solver_analysis_lifecycle.ps1')
. (Join-Path $projectRoot 'runtime\particle_table_identity.ps1')
function Resolve-Input([object]$Config,[string]$Name){$m=$Config.inputs.PSObject.Properties[$Name];if($null-eq$m){throw "Source run config lacks input $Name."};$v=[string]$m.Value;if([IO.Path]::IsPathRooted($v)){return [IO.Path]::GetFullPath($v)};[IO.Path]::GetFullPath((Join-Path ([string]$Config.project_root) $v))}
function Copy-ModeInput([object[]]$Pairs){Copy-CrossSolverAnalysisInputs -Pairs $Pairs}
$short=if($Mode -eq 'transport_no_collision'){'no-collision'}else{'interface-readiness'}
if([string]::IsNullOrWhiteSpace($RunId)){$RunId=(Get-Date -Format 'yyyyMMdd_HHmmss')+"__analysis__cross__rf-transport__$short"}
$software=@('COMSOL 6.4','SIMION 2020','Python 3.11')
$package=New-CrossSolverAnalysisPackage -Python $python -RepoRoot $repoRoot -ArtifactRoot $artifactRoot -RunId $RunId -PackageMode "${Mode}_cross_solver_comparison" -Software $software
$inputDir,$resultDir=$package.input_dir,$package.result_dir;$runConfigPath,$summaryPath=$package.run_config,$package.summary;$decisionStatus='NOT_EVALUATED';$role=if($Mode -eq 'transport_no_collision'){'rf_quadrupole_no_collision_cross_solver'}else{'rf_quadrupole_interface_readiness_cross_solver'}
try{
  $source=Get-CrossSolverSourcePair -Python $python -RepoRoot $repoRoot -ArtifactRoot $artifactRoot -ComsolRunId $ComsolRunId -SimionRunId $SimionRunId
  $cc,$sc=$source.comsol.config,$source.simion.config;$cp,$sp=$source.comsol.config_path,$source.simion.config_path;$cr,$sr=$source.comsol.run,$source.simion.run
  $modeFile=Join-Path $projectRoot "config\modes\$Mode.json"
  $frozen=New-CrossSolverFrozenPathSet -InputDir $inputDir -AnalyzerRelativePath 'projects\rf_quadrupole_ion_optics\workflows\cross_solver\evaluate.py' -ModeFilename 'mode_contract.json'
  $base=@(@((Join-Path $PSScriptRoot 'evaluate.py'),$frozen.analyzer),@((Join-Path $projectRoot 'analysis\particle_state_comparison_core.py'),$frozen.core),@((Join-Path $projectRoot 'workflows\__init__.py'),(Join-Path $frozen.module_root 'projects\rf_quadrupole_ion_optics\workflows\__init__.py')),@((Join-Path $PSScriptRoot '__init__.py'),(Join-Path $frozen.module_root 'projects\rf_quadrupole_ion_optics\workflows\cross_solver\__init__.py')),@($modeFile,$frozen.mode),@($source.comsol.manifest,$frozen.comsol_manifest),@($source.simion.manifest,$frozen.simion_manifest),@($cp,$frozen.comsol_config),@($sp,$frozen.simion_config),@((Join-Path $cr 'results\particle_state.csv'),$frozen.comsol_state),@((Join-Path $sr 'results\particle_state.csv'),$frozen.simion_state),@((Join-Path $projectRoot 'runtime\cross_solver_analysis_lifecycle.ps1'),$frozen.support))
  $arguments=@('--comsol',$frozen.comsol_state,'--simion',$frozen.simion_state,'--mode-contract',$frozen.mode)
  $inputs=[ordered]@{analyzer=$frozen.analyzer;comparison_core=$frozen.core;mode_contract=$frozen.mode;comsol_manifest=$frozen.comsol_manifest;simion_manifest=$frozen.simion_manifest;comsol_run_config=$frozen.comsol_config;simion_run_config=$frozen.simion_config;comsol_particle_state=$frozen.comsol_state;simion_particle_state=$frozen.simion_state;analysis_lifecycle_support=$frozen.support}
  if($Mode -eq 'transport_no_collision'){
    if($cc.role-ne'multipole_resolved_comsol_run_config'-or $sc.role-ne'multipole_resolved_simion_run_config'-or $cc.mode-ne'resolved_design_transport'-or $sc.mode-ne'resolved_design_transport'){throw 'No-collision comparison accepts only resolved multipole transport runs.'}
    foreach($config in @($cc,$sc)){if($config.parameters.design_profile_id-ne'official_transport'){throw 'No-collision source run design profile is not official_transport.'}}
    foreach($field in @('parent_resolved_design_sha256','particle_source_sha256','source_family_sha256','operating_point_id')){if([string]$cc.provenance.$field-ne[string]$sc.provenance.$field){throw "No-collision source provenance differs at $field."}}
    $resolved=Resolve-Input $cc 'multipole_resolved_design';$particles=Resolve-Input $cc 'particle_source';$sresolved=Resolve-Input $sc 'multipole_resolved_design';$sparticles=Resolve-Input $sc 'particle_source'
    if((Get-RunFileSha256 $resolved)-ne(Get-RunFileSha256 $sresolved)){throw 'No-collision source resolved designs differ.'};if((Get-RunFileSha256 $particles)-ne(Get-RunFileSha256 $sparticles)){throw 'No-collision source particle files differ.'}
    $metadata=Resolve-Input $cc 'particle_source_metadata';$count=[int]((Get-Content $metadata -Raw -Encoding UTF8|ConvertFrom-Json).particle_count);if($count-le0){throw 'No-collision particle source count is missing or empty.'}
    $fres=Join-Path $inputDir 'resolved_design.json';$fpart=Join-Path $inputDir 'particles.dat';$fmeta=Join-Path $inputDir 'particle_source_metadata.json';$fpolicy=Join-Path $inputDir 'particle_count_policy.json'
    $base+=@(@($resolved,$fres),@($particles,$fpart),@($metadata,$fmeta),@((Join-Path $repoRoot 'common\contracts\particle_count_policy.json'),$fpolicy));$arguments+=@('--resolved',$fres,'--particle-count-policy',$fpolicy,'--particles',$fpart,'--particle-count',[string]$count);$inputs.resolved_design=$fres;$inputs.particle_table=$fpart;$inputs.particle_source_metadata=$fmeta;$inputs.particle_count_policy=$fpolicy;$role='rf_quadrupole_no_collision_cross_solver';$resultName='no_collision_cross_solver.json';$censusName='no_collision_particle_event_census.csv'
  }else{
    if($cc.role-ne'rf_quadrupole_comsol_run_config'-or $sc.role-ne'rf_quadrupole_simion_run_config'-or $cc.mode-ne$Mode-or $sc.mode-ne$Mode){throw 'Interface comparison accepts only interface transport run configs.'};if($cc.operating_point-ne$sc.operating_point){throw 'COMSOL and SIMION operating points differ.'}
    $cb=Join-Path $inputDir 'comsol_particle_source_binding.json';$sb=Join-Path $inputDir 'simion_particle_source_binding.json';$identity=Assert-RfTransportParticleTableIdentity -Python $python -RepoRoot $repoRoot -ComsolRunConfig $cc -SimionRunConfig $sc -ComsolBindingOutput $cb -SimionBindingOutput $sb -ExplicitIon11Path $ParticleTablePath
    $cres=Resolve-Input $cc 'resolved_design';$sres=Resolve-Input $sc 'resolved_design';$fcr=Join-Path $inputDir 'comsol_resolved_design.json';$fsr=Join-Path $inputDir 'simion_resolved_design.json';$fion=Join-Path $inputDir 'particles.ion';$fcan=Join-Path $inputDir 'particles.csv';$base+=@(@($cres,$fcr),@($sres,$fsr),@($identity.ion11_path,$fion),@($identity.canonical10_path,$fcan));$drive=Get-CrossSolverResolvedDrive -ComsolResolvedDesign $cres -SimionResolvedDesign $sres;if([double]::IsNaN($FrequencyHz)){$FrequencyHz=[double]$drive.frequency_hz}elseif($FrequencyHz-ne[double]$drive.frequency_hz){throw 'Explicit frequency differs from the frozen resolved design.'}
    foreach($entry in @([pscustomobject]@{Solver='COMSOL';State=(Join-Path $cr 'results\particle_state.csv');Particles=$identity.ion11_path;Format='ion11'},[pscustomobject]@{Solver='SIMION';State=(Join-Path $sr 'results\particle_state.csv');Particles=$identity.canonical10_path;Format='canonical'})){& $python -m common.contracts.particle_state --state $entry.State --particles $entry.Particles --source-format $entry.Format --contract (Join-Path $projectRoot 'config\interface_contract.json') --frequency-hz $FrequencyHz --phase-rad $PhaseRad --solver $entry.Solver;if($LASTEXITCODE-ne0){throw "$($entry.Solver) particle-state contract failed."}}
    $base+=@(@((Join-Path $projectRoot 'config\interface_contract.json'),(Join-Path $inputDir 'interface_contract.json')));$arguments+=@('--particles',$fion,'--particle-count',[string]$identity.particle_count);$inputs.interface_contract=Join-Path $inputDir 'interface_contract.json';$inputs.particle_table_ion11=$fion;$inputs.particle_table_canonical10=$fcan;$inputs.comsol_resolved_design=$fcr;$inputs.simion_resolved_design=$fsr;$inputs.comsol_particle_source_binding=$cb;$inputs.simion_particle_source_binding=$sb;$count=$identity.particle_count;$role='rf_quadrupole_interface_readiness_cross_solver';$resultName='interface_readiness_cross_solver.json';$censusName='interface_particle_event_census.csv'
  }
  Copy-ModeInput $base;$comparison=Join-Path $resultDir $resultName;$census=Join-Path $resultDir $censusName;Write-RunJson -Path $runConfigPath -Depth 10 -Value ([ordered]@{schema_version=2;role="${role}_run_config";run_id=$RunId;project='rf_quadrupole_ion_optics';mode="${Mode}_cross_solver_comparison";project_root=$projectRoot;inputs=$inputs;parameters=[ordered]@{comsol_source_run_id=$ComsolRunId;simion_source_run_id=$SimionRunId;particle_count=$count};formal_gate_passed=$false})
  $stdout=Join-Path $package.log_dir 'analysis_stdout.txt';$stderr=Join-Path $package.log_dir 'analysis_stderr.txt';$arguments+=@('--output',$comparison,'--census-output',$census);Invoke-CrossSolverAnalyzer -Python $python -AnalyzerModule 'projects.rf_quadrupole_ion_optics.workflows.cross_solver.evaluate' -ModuleRoot $frozen.module_root -Arguments $arguments -Stdout $stdout -Stderr $stderr -RequiredOutputs @($comparison,$census)
  $report=Get-Content $comparison -Raw -Encoding UTF8|ConvertFrom-Json;if($report.execution_status-ne'success'-or $report.status-notin@('PASS','FAIL','NOT_EVALUATED')){throw 'Cross-solver comparison result identity or status is invalid.'};$decisionStatus=[string]$report.status;$summary=[ordered]@{schema_version=2;role="${role}_summary";status='success';execution_status='success';decision_status=$decisionStatus;comparison="results/$resultName";census="results/$censusName"};Complete-CrossSolverAnalysis -Python $python -RepoRoot $repoRoot -RunConfig $runConfigPath -Summary $summaryPath -SummaryValue $summary -Outputs @($comparison,$census) -Software $software -Logs @($stdout,$stderr)
}catch{Complete-FailedRun -Python $python -RepoRoot $repoRoot -RunConfig $runConfigPath -Summary $summaryPath -SummaryRole "${role}_summary" -Reason $_.Exception.Message -Software $software;throw}
if($decisionStatus-ne'PASS'){throw "Cross-solver comparison completed with decision $decisionStatus."};"STATUS=PASS RUN_ID=$RunId"
