[CmdletBinding()]
param(
  [Parameter(Mandatory)][string]$GeometryReviewRunPath,
  [string]$RunId = '',
  [string]$SimionExe = '',
  [string]$PythonExe = ''
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Copy-RequiredRunInput { param([Parameter(Mandatory)][string]$Source,[Parameter(Mandatory)][string]$Destination,[Parameter(Mandatory)][string]$Label)
  if(-not(Test-Path -LiteralPath $Source -PathType Leaf)){throw "$Label is missing: $Source"};Copy-VerifiedRunInput -Source $Source -Destination $Destination
}
function Invoke-MrtofPython { param([Parameter(Mandatory)][string[]]$Arguments)
  Push-Location -LiteralPath $repoRoot;$savedPythonPath=$env:PYTHONPATH
  try{$env:PYTHONPATH=$repoRoot;& $python @Arguments;if($LASTEXITCODE-ne 0){throw "MR-TOF Python failed: $($Arguments -join ' ')"}}finally{$env:PYTHONPATH=$savedPythonPath;Pop-Location}
}
function Invoke-MrtofSimionStep { param([Parameter(Mandatory)][string]$Stage,[Parameter(Mandatory)][string[]]$Arguments)
  Push-Location -LiteralPath $solverDir
  try{& $simion @Arguments 2>&1|Tee-Object -FilePath (Join-Path $logDir "$Stage.log");if($LASTEXITCODE-ne 0){throw "SIMION stage failed: $Stage"}}finally{Pop-Location}
}

$projectId='parallel_mirror_dual_stripe_mr_tof';$repoRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path;$workspaceRoot=Split-Path -Parent $repoRoot
$python=if($PythonExe){[IO.Path]::GetFullPath($PythonExe)}else{Join-Path $repoRoot '.venv\Scripts\python.exe'};$simion=if($SimionExe){[IO.Path]::GetFullPath($SimionExe)}else{Join-Path $env:ProgramFiles 'SIMION-2020\simion.exe'}
if(-not(Test-Path -LiteralPath $simion -PathType Leaf)){throw "SIMION executable is missing: $simion"}
$geometryRun=(Resolve-Path -LiteralPath $GeometryReviewRunPath).Path;$geometrySimion=Join-Path $geometryRun 'simion';$geometryResults=Join-Path $geometryRun 'results'
$requiredNames=@('mrtof_analyzer.pa#','mrtof_analyzer.pa0','mrtof_accelerator.pa#','mrtof_accelerator.pa0','mrtof_detector.pa#','first_prism_l0_receipt.json','mrtof_first_prism_l0.lua','mrtof_first_prism_l0.operating_point.lua','mrtof_first_prism_l0.voltage_map.lua','mrtof_first_prism_l0.fly2','mrtof_first_prism_entry_center.fly2','prototype_input_manifest.json','simion_prototype_contract.json')
foreach($path in @((Join-Path $geometrySimion 'mrtof_three_component_candidate.iob'),(Join-Path $geometrySimion 'three_component_geometry_review.json'),(Join-Path $geometryResults 'iob_structure_report.txt'))+($requiredNames|ForEach-Object{Join-Path $geometrySimion $_})){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Completed geometry-review input is missing: $path"}}
if([string]::IsNullOrWhiteSpace($RunId)){$RunId=(Get-Date -Format 'yyyyMMdd_HHmmss')+'__sim__simion__mrtof-first-prism-l0-n1'}

. (Join-Path $repoRoot 'common\contracts\run_artifact_support.ps1');. (Join-Path $repoRoot 'common\host_execution_lease.ps1')
$package=New-RunPackage -Python $python -RepoRoot $repoRoot -ArtifactRoot (Join-Path $workspaceRoot "artifacts\projects\$projectId") -RunId $RunId -Project $projectId -Mode 'three_component_first_prism_l0_flight' -Software @('SIMION 2020','Python 3.11') -RetentionContractEnabled -RetentionClass solver_review -RetentionReason 'Native first-prism interface evidence retains the rebuilt IOB, loaded PA0 arrays, and raw log.' -AdditionalDirectories @('simion') -UseShortExecutionPath
$runDir=$package.run_dir;$inputDir=$package.input_dir;$resultDir=$package.result_dir;$logDir=$package.log_dir;$solverDir=Join-Path $runDir 'simion';$runConfig=$package.run_config;$summary=$package.summary;$artifactRoot=Join-Path $workspaceRoot 'artifacts';$terminalized=$false;$failureStage='preflight';$hostExecutionOutcome='failed';$hostExecutionLease=$null
try{
  $failureStage='capacity_preflight';$sources=@((Join-Path $geometrySimion 'mrtof_three_component_candidate.iob'),(Join-Path $geometrySimion 'three_component_geometry_review.json'),(Join-Path $geometryResults 'iob_structure_report.txt'))+($requiredNames|ForEach-Object{Join-Path $geometrySimion $_})+@((Join-Path $repoRoot 'projects\parallel_mirror_dual_stripe_mr_tof\simion\inspect_three_component_iob.lua'),(Join-Path $repoRoot 'projects\parallel_mirror_dual_stripe_mr_tof\simion\run_iob_flight.lua'),(Join-Path $repoRoot 'projects\parallel_mirror_dual_stripe_mr_tof\analysis\first_prism_l0_result.py'))
  [int64]$copyBytes=0;foreach($source in $sources){$copyBytes+=[int64](Get-Item -LiteralPath $source).Length}
  $startup=Invoke-ArtifactCapacityGate -Python $python -RepoRoot $repoRoot -ArtifactRoot $artifactRoot -RequiredHeadroomBytes $copyBytes -ProtectedPaths @($package.artifact_run_dir);$startupPath=Join-Path $resultDir 'artifact_capacity_gate_startup.json';Write-RunJson -Path $startupPath -Depth 14 -Value $startup
  $failureStage='freeze_inputs';foreach($name in $requiredNames){Copy-RequiredRunInput -Source (Join-Path $geometrySimion $name) -Destination (Join-Path $solverDir $name) -Label "reviewed $name"|Out-Null};$iob=Copy-RequiredRunInput -Source (Join-Path $geometrySimion 'mrtof_three_component_candidate.iob') -Destination (Join-Path $solverDir 'mrtof_first_prism_l0.iob') -Label 'reviewed PA0 IOB';$review=Copy-RequiredRunInput -Source (Join-Path $geometrySimion 'three_component_geometry_review.json') -Destination (Join-Path $solverDir 'three_component_geometry_review.json') -Label 'geometry review';$report=Copy-RequiredRunInput -Source (Join-Path $geometryResults 'iob_structure_report.txt') -Destination (Join-Path $solverDir 'iob_structure_report.txt') -Label 'geometry review report'
  foreach($name in @('inspect_three_component_iob.lua','run_iob_flight.lua')){Copy-RequiredRunInput -Source (Join-Path $PSScriptRoot $name) -Destination (Join-Path $solverDir $name) -Label "SIMION $name"|Out-Null};$analyzer=Copy-RequiredRunInput -Source (Join-Path $repoRoot 'projects\parallel_mirror_dual_stripe_mr_tof\analysis\first_prism_l0_result.py') -Destination (Join-Path $solverDir 'first_prism_l0_result.py') -Label 'first-prism result analyzer'
  if(-not(Test-RunFilesIdentical -Left (Join-Path $solverDir 'mrtof_first_prism_l0.fly2') -Right (Join-Path $geometrySimion 'mrtof_first_prism_l0.fly2'))){throw 'Frozen first-prism Fly2 differs from selected source.'}
  $config=Get-Content -LiteralPath $runConfig -Raw -Encoding UTF8|ConvertFrom-Json -AsHashtable;$config.inputs=[ordered]@{reviewed_iob=$iob;geometry_review=$review;geometry_review_report=$report;source_manifest=(Join-Path $solverDir 'prototype_input_manifest.json');consumed_fly2=(Join-Path $solverDir 'mrtof_first_prism_l0.fly2')};$config.parameters.source_key='first_prism_iob_fly2';Write-RunJson -Path $runConfig -Value $config
  $failureStage='derive_iob_pose';$poseCode="import json,sys; from pathlib import Path; from projects.parallel_mirror_dual_stripe_mr_tof.analysis.split_candidate_geometry import resolve_split_iob_origins; p=Path(sys.argv[1]); c=json.loads(p.read_text(encoding='utf-8')); json.dump({'origins_mm':resolve_split_iob_origins(p),'mesh_mm_per_gu':c['simion']['component_mesh_mm_per_gu']},open(sys.argv[2],'w',encoding='utf-8'),indent=2)";$pose=Join-Path $resultDir 'resolved_iob_pose.json';Invoke-MrtofPython -Arguments @('-c',$poseCode,(Join-Path $solverDir 'simion_prototype_contract.json'),$pose);$poseData=Get-Content -LiteralPath $pose -Raw -Encoding UTF8|ConvertFrom-Json;$origins=@('analyzer','accelerator','detector')|ForEach-Object{@($poseData.origins_mm.$_)}|ForEach-Object{$_};$mesh=@('analyzer','accelerator','detector')|ForEach-Object{@($poseData.mesh_mm_per_gu.$_)}|ForEach-Object{$_}
  $structure=Join-Path $resultDir 'first_prism_iob_structure_report.txt';$failureStage='inspect_iob';$hostExecutionLease=Enter-HostExecutionLease -Role SIMION -RunId $RunId;Invoke-MrtofSimionStep -Stage 'inspect_iob' -Arguments (@('--nogui','--noprompt','lua',(Join-Path $solverDir 'inspect_three_component_iob.lua'),'--',$iob,$structure)+$origins+$mesh);if(-not(Select-String -LiteralPath $structure -SimpleMatch 'STATUS=PASS' -Quiet)){throw 'Reused first-prism IOB inspection did not pass.'};if(-not(Test-RunFilesIdentical -Left (Join-Path $solverDir 'mrtof_first_prism_l0.fly2') -Right (Join-Path $solverDir 'mrtof_first_prism_entry_center.fly2'))){throw 'IOB companion Fly2 does not equal the declared first-prism entry source.'}
  $failureStage='native_first_prism_flight';Invoke-MrtofSimionStep -Stage 'native_first_prism_flight' -Arguments @('--nogui','--noprompt','lua',(Join-Path $solverDir 'run_iob_flight.lua'),$iob)
  $rawLog=Join-Path $logDir 'native_first_prism_flight.log';$result=Join-Path $resultDir 'first_prism_l0_result.json';$failureStage='first_prism_result';Invoke-MrtofPython -Arguments @($analyzer,'--log',$rawLog,'--input-manifest',(Join-Path $solverDir 'prototype_input_manifest.json'),'--receipt',(Join-Path $solverDir 'first_prism_l0_receipt.json'),'--output',$result)
  Write-RunJson -Path $summary -Value ([ordered]@{schema_version=1;role='mrtof_three_component_first_prism_l0_flight';status='success';qualification='prototype_first_prism_interface_only';particle_count=1;reason='One post-accelerator particle reached the declared first-prism interface. No return, K=25, transmission, time focus, or resolution claim is made.'});$retention=Apply-RunArtifactRetention -Python $python -RepoRoot $repoRoot -RunConfig $runConfig;$failureStage='capacity_terminal';$maximum=[int64](Get-ChildItem -LiteralPath $package.artifact_run_dir -Recurse -File|Measure-Object Length -Sum).Sum;$terminal=Invoke-ArtifactCapacityGate -Python $python -RepoRoot $repoRoot -ArtifactRoot $artifactRoot -ProtectedPaths @($package.artifact_run_dir) -KnownMeasuredBytes ([int64]$startup.measured_after_bytes) -MaximumNewArtifactBytes $maximum;$terminalPath=Join-Path $resultDir 'artifact_capacity_gate_terminal.json';Write-RunJson -Path $terminalPath -Depth 14 -Value $terminal;Write-VerifiedRunManifest -Python $python -RepoRoot $repoRoot -RunConfig $runConfig -Status success -Software @('SIMION 2020','Python 3.11') -Outputs @($summary,$pose,$structure,$rawLog,$result,$startupPath,$terminalPath,$retention);$terminalized=$true;$hostExecutionOutcome='success';Write-Host "MRTOF_FIRST_PRISM_L0=PASS RUN_ID=$RunId"
}catch{if(-not$terminalized){Complete-FailedRun -Python $python -RepoRoot $repoRoot -RunConfig $runConfig -Summary $summary -SummaryRole 'mrtof_three_component_first_prism_l0_flight' -Reason $_.Exception.Message -Software @('SIMION 2020','Python 3.11') -Status failed -FailureStage $failureStage;$terminalized=$true};throw}finally{if(-not$terminalized-and(Test-Path -LiteralPath $runConfig -PathType Leaf)){Complete-FailedRun -Python $python -RepoRoot $repoRoot -RunConfig $runConfig -Summary $summary -SummaryRole 'mrtof_three_component_first_prism_l0_flight' -Reason 'Runner stopped before terminal evidence publication.' -Software @('SIMION 2020','Python 3.11') -Status interrupted -FailureStage $failureStage;$hostExecutionOutcome='interrupted'};if($null-ne$hostExecutionLease){Exit-HostExecutionLease -Lease $hostExecutionLease -Outcome $hostExecutionOutcome -RunId $RunId};Remove-RunPackageExecutionAlias -Package $package}
