local path=assert(arg[1], 'raw PA required')
local nx=assert(tonumber(arg[2]), 'nx required')
local ny=assert(tonumber(arg[3]), 'ny required')
local nz=assert(tonumber(arg[4]), 'nz required')
local pa=assert(simion.pas:open(path))
assert(pa.nx==nx and pa.ny==ny and pa.nz==nz, 'coarse raw grid differs')
assert(pa.dx_mm==1 and pa.dy_mm==1 and pa.dz_mm==1, 'coarse raw mesh differs')
assert(pa.symmetry=='3dplanar', 'coarse raw must retain its full bilateral domain')
pa:close()
print(string.format('MRTOF_COARSE_RAW_VERIFY=PASS dimensions=%dx%dx%d symmetry=3dplanar',nx,ny,nz))
