reportPath=getenv('COMSOL_BOOTSTRAP_REPORT');
assert(~isempty(reportPath), ...
    'COMSOL_BOOTSTRAP_REPORT must identify the shared launcher report.');
writeReportAtomically(reportPath,sprintf('STATUS=RUNNING\n'));

taskDir=fileparts(mfilename('fullpath'));
projectRoot=fileparts(fileparts(taskDir));
addpath(projectRoot);
addpath(fullfile(projectRoot,'comsol'));
try
    runConfigPath=getenv('RFQUAD_RUN_CONFIG');
    assert(~isempty(runConfigPath) && isfile(runConfigPath), ...
        'RFQUAD_RUN_CONFIG must identify a frozen run config.');
    runConfig=jsondecode(fileread(runConfigPath));
    assert(strcmp(requiredText(runConfig,'role'), ...
        'rf_quadrupole_comsol_run_config'), ...
        'Release-construction gate run-config role mismatch.');
    assert(requiredFinite(runConfig,'particles')==100, ...
        'Release-construction gate requires exactly N=100.');
    parameters=requiredStruct(runConfig,'parameters');
    assert(strcmp(requiredText(parameters,'execution_stage'), ...
        'release_construction_gate'), ...
        'Release-construction gate execution-stage mismatch.');

    inputs=requiredStruct(runConfig,'inputs');
    particleTable=requiredFile(inputs,'particle_table');
    ions=readmatrix(particleTable,'FileType','text','Delimiter',',');
    assert(isequal(size(ions),[100 11]) && all(isfinite(ions),'all'), ...
        'Release-construction gate requires one finite 100-by-11 ION11 table.');
    assert(numel(unique(ions(:,1)))==100, ...
        'Release-construction gate requires the 100 frozen independent birth times.');

    control=struct( ...
        'role','rf_release_construction_gate_control', ...
        'stop_after_release_construction',true, ...
        'breadcrumbs_path',fullfile(requiredText(runConfig,'logs_dir'), ...
            'release_construction_breadcrumbs.jsonl'), ...
        'model_path',fullfile(requiredText(runConfig,'comsol_dir'), ...
            'rf_quadrupole_collision_cooling__release-construction-gate.mph'), ...
        'result_path',fullfile(requiredText(runConfig,'results_dir'), ...
            'release_construction_gate.json'));
    result=solve_deterministic_rf_quadrupole_particles(runConfig,control);
    assert(strcmp(result.status,'success') && ...
        result.particles==100 && result.release_tag_count==100 && ...
        result.release_file_count==100 && ...
        result.unique_birth_time_count==100 && ...
        result.unique_release_time_expression_count==100 && ...
        result.breadcrumb_count==1000 && ...
        result.stationary_study_present && result.stationary_solver_present && ...
        ~result.electric_force_present && ...
        ~result.particle_study_present && ~result.particle_solver_present, ...
        'Release-construction gate result does not preserve its fixed N=100 boundary.');
    writeReportAtomically(reportPath,sprintf([ ...
        'STATUS=PASS\nPARTICLES=100\nRELEASE_TAGS=100\n' ...
        'PARTICLE_STUDY_PRESENT=0\n']));
catch ME
    writeReportAtomically(reportPath,sprintf('STATUS=FAIL\nERROR=%s\n', ...
        getReport(ME,'extended')));
    rethrow(ME)
end

function writeReportAtomically(path,text)
directory=fileparts(path);
if ~isfolder(directory),mkdir(directory);end
temporaryPath=[path '.tmp'];
fid=fopen(temporaryPath,'w','n','UTF-8');
assert(fid>=0,'Could not create temporary task report: %s',temporaryPath);
try
    written=fprintf(fid,'%s',text);
catch ME
    fclose(fid);
    rethrow(ME)
end
closeStatus=fclose(fid);
expectedBytes=numel(unicode2native(text,'UTF-8'));
assert(written==expectedBytes, ...
    'Task report write was incomplete: %s',temporaryPath);
assert(closeStatus==0, ...
    'Task report close/flush failed: %s',temporaryPath);
[moved,message]=movefile(temporaryPath,path,'f');
assert(moved,'Could not publish task report: %s',message);
end

function value=requiredStruct(parent,fieldName)
assert(isstruct(parent) && isfield(parent,fieldName) && ...
    isstruct(parent.(fieldName)) && isscalar(parent.(fieldName)), ...
    '%s must be a scalar struct.',fieldName);
value=parent.(fieldName);
end

function value=requiredText(parent,fieldName)
assert(isstruct(parent) && isfield(parent,fieldName), ...
    '%s is required.',fieldName);
raw=parent.(fieldName);
assert((ischar(raw) || (isstring(raw) && isscalar(raw))) && ...
    ~isempty(strtrim(char(raw))), ...
    '%s must be non-empty scalar text.',fieldName);
value=char(raw);
end

function path=requiredFile(parent,fieldName)
path=requiredText(parent,fieldName);
assert(isfile(path),'%s does not identify a frozen file: %s',fieldName,path);
end

function value=requiredFinite(parent,fieldName)
assert(isstruct(parent) && isfield(parent,fieldName), ...
    '%s is required.',fieldName);
value=parent.(fieldName);
assert(isnumeric(value) && isscalar(value) && isfinite(value), ...
    '%s must be one finite numeric scalar.',fieldName);
value=double(value);
end
