function manifest = oatof_cad_export_manifest()
%OATOF_CAD_EXPORT_MANIFEST Physical oa-TOF bodies eligible for CAD export.
%
% The oa-TOF model uses zero-thickness internal boundaries for grid1,
% grid2, entgrid, and midgrid.  They are deliberately excluded: they are
% simulation abstractions, not manufacturable solids.  Vacuum domains and
% all result/physics nodes are likewise never CAD-exported.

    featureTag = [ ...
        "repeller"; "accelshield"; ...
        "accelring_1"; "accelring_2"; "accelring_3"; "accelring_4"; "accelring_5"; ...
        "flighttubewall"; ...
        "ring1_1"; "ring1_2"; "ring1_3"; "ring1_4"; "ring1_5"; ...
        "ring2_1"; "ring2_2"; "ring2_3"; "ring2_4"; "ring2_5"; ...
        "backplate"; "detector"];

    component = [ ...
        "repeller"; "accelerator_shield"; ...
        "accelerator_ring"; "accelerator_ring"; "accelerator_ring"; "accelerator_ring"; "accelerator_ring"; ...
        "flight_tube_shield"; ...
        "reflectron_stage1_ring"; "reflectron_stage1_ring"; "reflectron_stage1_ring"; "reflectron_stage1_ring"; "reflectron_stage1_ring"; ...
        "reflectron_stage2_ring"; "reflectron_stage2_ring"; "reflectron_stage2_ring"; "reflectron_stage2_ring"; "reflectron_stage2_ring"; ...
        "reflectron_backplate"; "detector"];

    manifest = table(featureTag, component, ...
        'VariableNames', {'FeatureTag', 'Component'});
end
