function selections = configure_comsol_segment_hybrid_mesh(comp, mesh, geometryTag, numerics, ...
    sweepGeometryTags, rodBoundarySelectionTags, sweepRodBoundarySelectionTags, ...
    interfaceBoundarySelectionTags)
%CONFIGURE_COMSOL_SEGMENT_HYBRID_MESH Mesh invariant rod interiors with prisms.
%
% Geometry partitions must already exist and the geometry must have been
% built.  Each sweep partition lies strictly inside one physical rod
% segment, leaving rod ends, intersegment gaps, aperture plates and
% external regions to the tetrahedral transition mesh.

strategy = numerics.mesh.hybrid;
localized = isfield(strategy, 'sensitive_region');
exitInterfaceRefinement = false;
assert(~isempty(sweepGeometryTags), ...
    'common:multipole:HybridMeshPartitions', ...
    'Segment-hybrid meshing requires at least one swept partition.');
assert(~isempty(rodBoundarySelectionTags), ...
    'common:multipole:HybridMeshRodBoundaries', ...
    'Segment-hybrid meshing requires explicit rod-boundary selections.');
assert(numel(sweepRodBoundarySelectionTags) == numel(sweepGeometryTags), ...
    'common:multipole:HybridMeshSweepRodBoundaries', ...
    'Each swept partition requires its own rod-boundary selection.');
positive = [strategy.core_radius_mm, strategy.radial_core_and_rod_hmax_mm, ...
    strategy.outer_vacuum_hmax_mm, strategy.transition_and_end_tetra_hmax_mm, ...
    strategy.minimum_element_size_mm];
assert(all(isfinite(positive) & positive > 0), ...
    'common:multipole:HybridMeshSize', ...
    'Segment-hybrid mesh dimensions must be positive and finite.');
assert(strategy.axial_layers_per_swept_segment >= 1 && ...
    strategy.axial_layers_per_swept_segment == round(strategy.axial_layers_per_swept_segment), ...
    'common:multipole:HybridMeshLayers', ...
    'Segment-hybrid axial layers must be a positive integer.');
if localized
    sensitive = strategy.sensitive_region;
    sensitivePositive = [sensitive.particle_corridor_radius_mm, ...
        sensitive.maximum_element_size_mm];
    assert(all(isfinite(sensitivePositive) & sensitivePositive > 0), ...
        'common:multipole:HybridMeshSensitiveSize', ...
        'Localized sensitive-region dimensions must be positive and finite.');
    assert(sensitive.maximum_element_size_mm <= ...
        strategy.radial_core_and_rod_hmax_mm && ...
        sensitive.maximum_element_size_mm <= ...
        strategy.transition_and_end_tetra_hmax_mm, ...
        'common:multipole:HybridMeshSensitiveRefinement', ...
        'Sensitive-region size must not exceed either surrounding core size.');
    assert(~isempty(interfaceBoundarySelectionTags), ...
        'common:multipole:HybridMeshInterfaceBoundaries', ...
        'Localized meshing requires explicit entrance and exit plate boundaries.');
    exitInterfaceRefinement = isfield( ...
        sensitive, 'exit_interface_refinement');
    if exitInterfaceRefinement
        exitRefinement = sensitive.exit_interface_refinement;
        exitRefinementPositive = [ ...
            exitRefinement.upstream_extent_from_rod_exit_mm, ...
            exitRefinement.maximum_element_size_mm];
        assert(all(isfinite(exitRefinementPositive) & ...
            exitRefinementPositive > 0) && ...
            isfinite(exitRefinement.downstream_extent_from_handoff_mm) && ...
            exitRefinement.downstream_extent_from_handoff_mm >= 0, ...
            'common:multipole:HybridMeshExitRefinementSize', ...
            'Exit-interface refinement dimensions are invalid.');
        assert(exitRefinement.maximum_element_size_mm < ...
            sensitive.maximum_element_size_mm, ...
            'common:multipole:HybridMeshExitRefinementOrder', ...
            ['Exit-interface refinement size must be strictly smaller than ' ...
            'the full-length particle-corridor size.']);
    end
end

coreGeometrySelection = [geometryTag '_meshCore_dom'];
if localized
    sensitiveCorridorGeometrySelection = ...
        [geometryTag '_meshSensitiveCorridor_dom'];
end
if exitInterfaceRefinement
    exitRefinementGeometrySelection = ...
        [geometryTag '_meshSensitiveExit_dom'];
end
sweepSelections = cell(1, numel(sweepGeometryTags));
sweepCoreSelections = cell(1, numel(sweepGeometryTags));
sweepSensitiveSelections = cell(1, numel(sweepGeometryTags));
sweepExitRefinementSelections = cell(1, numel(sweepGeometryTags));
for index = 1:numel(sweepGeometryTags)
    sweepSelections{index} = sprintf('sel_mesh_sweep_%d_vac', index);
    create_intersection(comp, sweepSelections{index}, ...
        {'sel_vac', [geometryTag '_' sweepGeometryTags{index} '_dom']});
    sweepCoreSelections{index} = sprintf('sel_mesh_sweep_%d_core_vac', index);
    create_intersection(comp, sweepCoreSelections{index}, ...
        {sweepSelections{index}, coreGeometrySelection});
    if localized
        sweepSensitiveSelections{index} = ...
            sprintf('sel_mesh_sweep_%d_sensitive_vac', index);
        create_intersection(comp, sweepSensitiveSelections{index}, ...
            {sweepSelections{index}, sensitiveCorridorGeometrySelection});
    end
    if exitInterfaceRefinement
        sweepExitRefinementSelections{index} = ...
            sprintf('sel_mesh_sweep_%d_exit_refinement_vac', index);
        create_intersection(comp, sweepExitRefinementSelections{index}, ...
            {sweepSelections{index}, exitRefinementGeometrySelection});
    end
end

comp.selection.create('sel_mesh_swept_vac', 'Union');
comp.selection('sel_mesh_swept_vac').set('entitydim', 3);
comp.selection('sel_mesh_swept_vac').set('input', sweepSelections);
comp.selection.create('sel_mesh_tet_vac', 'Difference');
comp.selection('sel_mesh_tet_vac').set('entitydim', 3);
comp.selection('sel_mesh_tet_vac').set('add', {'sel_vac'});
comp.selection('sel_mesh_tet_vac').set('subtract', {'sel_mesh_swept_vac'});
create_intersection(comp, 'sel_mesh_tet_core_vac', ...
    {'sel_mesh_tet_vac', coreGeometrySelection});
if localized
    create_intersection(comp, 'sel_mesh_tet_sensitive_vac', ...
        {'sel_mesh_tet_vac', sensitiveCorridorGeometrySelection});
end
if exitInterfaceRefinement
    create_intersection(comp, 'sel_mesh_tet_exit_refinement_vac', ...
        {'sel_mesh_tet_vac', exitRefinementGeometrySelection});
end
comp.selection.create('sel_mesh_rod_bnd', 'Union');
comp.selection('sel_mesh_rod_bnd').set('entitydim', 2);
comp.selection('sel_mesh_rod_bnd').set('input', rodBoundarySelectionTags);
if localized
    comp.selection.create('sel_mesh_interface_bnd', 'Union');
    comp.selection('sel_mesh_interface_bnd').set('entitydim', 2);
    comp.selection('sel_mesh_interface_bnd').set( ...
        'input', interfaceBoundarySelectionTags);
end

mesh.feature('size').set('hauto', numerics.mesh.global_auto_level);
for index = 1:numel(sweepSelections)
    sweep = mesh.feature.create(sprintf('swe%d', index), 'Sweep');
    sweep.selection.geom(geometryTag, 3);
    sweep.selection.named(sweepSelections{index});
    sweep.set('facemethod', 'tri');
    add_size(sweep, sprintf('szOut%d', index), geometryTag, ...
        sweepSelections{index}, strategy.outer_vacuum_hmax_mm, ...
        strategy.minimum_element_size_mm);
    add_size(sweep, sprintf('szCore%d', index), geometryTag, ...
        sweepCoreSelections{index}, strategy.radial_core_and_rod_hmax_mm, ...
        strategy.minimum_element_size_mm);
    if localized
        add_size(sweep, sprintf('szSensitive%d', index), geometryTag, ...
            sweepSensitiveSelections{index}, sensitive.maximum_element_size_mm, ...
            strategy.minimum_element_size_mm);
    end
    if exitInterfaceRefinement && selection_has_entities( ...
            comp, sweepExitRefinementSelections{index})
        add_size(sweep, sprintf('szExit%d', index), geometryTag, ...
            sweepExitRefinementSelections{index}, ...
            exitRefinement.maximum_element_size_mm, ...
            strategy.minimum_element_size_mm);
    end
    if ~localized
        add_size(sweep, sprintf('szRod%d', index), geometryTag, ...
            sweepRodBoundarySelectionTags{index}, ...
            strategy.radial_core_and_rod_hmax_mm, ...
            strategy.minimum_element_size_mm, 2);
    end
    distribution = sweep.feature.create(sprintf('dist%d', index), 'Distribution');
    distribution.selection.geom(geometryTag, 3);
    distribution.selection.named(sweepSelections{index});
    distribution.set('type', 'number');
    distribution.set('numelem', round(strategy.axial_layers_per_swept_segment));
    distribution.set('equidistant', 'on');
end

tetrahedra = mesh.feature.create('ftet1', 'FreeTet');
tetrahedra.selection.geom(geometryTag, 3);
tetrahedra.selection.named('sel_mesh_tet_vac');
add_size(tetrahedra, 'szTetOut', geometryTag, 'sel_mesh_tet_vac', ...
    strategy.outer_vacuum_hmax_mm, strategy.minimum_element_size_mm);
add_size(tetrahedra, 'szTetCore', geometryTag, 'sel_mesh_tet_core_vac', ...
    strategy.transition_and_end_tetra_hmax_mm, strategy.minimum_element_size_mm);
if localized
    add_size(tetrahedra, 'szTetSensitive', geometryTag, ...
        'sel_mesh_tet_sensitive_vac', sensitive.maximum_element_size_mm, ...
        strategy.minimum_element_size_mm);
end
if exitInterfaceRefinement && selection_has_entities( ...
        comp, 'sel_mesh_tet_exit_refinement_vac')
    add_size(tetrahedra, 'szTetExit', geometryTag, ...
        'sel_mesh_tet_exit_refinement_vac', ...
        exitRefinement.maximum_element_size_mm, ...
        strategy.minimum_element_size_mm);
end
if ~localized
    add_size(tetrahedra, 'szTetRod', geometryTag, 'sel_mesh_rod_bnd', ...
        strategy.radial_core_and_rod_hmax_mm, ...
        strategy.minimum_element_size_mm, 2);
end

selections = struct( ...
    'sweep', {sweepSelections}, ...
    'sweep_core', {sweepCoreSelections}, ...
    'tetrahedral', 'sel_mesh_tet_vac', ...
    'tetrahedral_core', 'sel_mesh_tet_core_vac', ...
    'rod_boundary', 'sel_mesh_rod_bnd', ...
    'sweep_rod_boundary', {sweepRodBoundarySelectionTags});
if localized
    selections.sweep_sensitive = sweepSensitiveSelections;
    selections.tetrahedral_sensitive = 'sel_mesh_tet_sensitive_vac';
    selections.interface_boundary = 'sel_mesh_interface_bnd';
end
if exitInterfaceRefinement
    selections.sweep_exit_refinement = sweepExitRefinementSelections;
    selections.tetrahedral_exit_refinement = ...
        'sel_mesh_tet_exit_refinement_vac';
end
end

function create_intersection(comp, tag, inputs)
comp.selection.create(tag, 'Intersection');
comp.selection(tag).set('entitydim', 3);
comp.selection(tag).set('input', inputs);
end

function present = selection_has_entities(comp, selectionTag)
present = ~isempty(double(comp.selection(selectionTag).entities()));
end

function add_size(parent, tag, geometryTag, selectionTag, hmax, hmin, entityDimension)
if nargin < 7
    entityDimension = 3;
end
feature = parent.feature.create(tag, 'Size');
feature.selection.geom(geometryTag, entityDimension);
feature.selection.named(selectionTag);
feature.set('custom', 'on');
feature.set('hmaxactive', true);
feature.set('hmax', sprintf('%.17g[mm]', hmax));
feature.set('hminactive', true);
feature.set('hmin', sprintf('%.17g[mm]', hmin));
end
