param([Parameter(Mandatory=$true)][string]$CandidateRunId,[Parameter(Mandatory=$true)][string]$ReferenceRunId,[string]$RunId='')
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$projectRoot=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$repoRoot=(Resolve-Path (Join-Path $projectRoot '..\..')).Path;$workspaceRoot=Split-Path -Parent $repoRoot
$artifactRoot=Join-Path $workspaceRoot 'artifacts\projects\rf_quadrupole_collision_cooling';$sourceRoot=Join-Path $artifactRoot 'runs';$python=Join-Path $repoRoot '.venv\Scripts\python.exe'
foreach($sourceId in @($CandidateRunId,$ReferenceRunId)){& $python (Join-Path $repoRoot 'common\contracts\artifact_naming.py') run $sourceId;if($LASTEXITCODE -ne 0){throw "Invalid source run_id: $sourceId"}}
$candidateDir=Join-Path $sourceRoot $CandidateRunId;$referenceDir=Join-Path $sourceRoot $ReferenceRunId
$candidateManifest=Join-Path $candidateDir 'run_manifest.json';$referenceManifest=Join-Path $referenceDir 'run_manifest.json';$candidateEvents=Join-Path $candidateDir 'results\rf_continuous_shield_n100_events.csv';$referenceEvents=Join-Path $referenceDir 'results\rf_continuous_shield_n100_events.csv'
foreach($path in @($candidateManifest,$referenceManifest,$candidateEvents,$referenceEvents)){if(-not(Test-Path -LiteralPath $path -PathType Leaf)){throw "Required source evidence is missing: $path"}}
foreach($path in @($candidateManifest,$referenceManifest)){$manifest=Get-Content -LiteralPath $path -Raw -Encoding UTF8|ConvertFrom-Json;if($manifest.status -ne 'success' -or $manifest.mode -ne 'rf_continuous_grounded_shield_n100_mesh_sensitivity'){throw "Source is not a successful shield N=100 diagnostic: $path"}}
if([string]::IsNullOrWhiteSpace($RunId)){$RunId=(Get-Date -Format 'yyyyMMdd_HHmmss')+'__analysis__python__rf-continuous-shield-n100-mesh-sensitivity'}
& $python (Join-Path $repoRoot 'common\contracts\artifact_naming.py') run $RunId;if($LASTEXITCODE -ne 0){throw "Invalid run_id: $RunId"}
$runDir=Join-Path $sourceRoot $RunId;if(Test-Path -LiteralPath $runDir){throw "Run already exists: $runDir"};$inputDir=Join-Path $runDir 'inputs';$resultDir=Join-Path $runDir 'results';New-Item -ItemType Directory -Force -Path $inputDir,$resultDir|Out-Null
$analysis=Join-Path $inputDir 'compare_rf_continuous_shield_n100.py';$runner=Join-Path $inputDir 'run_rf_continuous_shield_n100_comparison.ps1.txt';Copy-Item (Join-Path $projectRoot 'analysis\compare_rf_continuous_shield_n100.py') $analysis;Copy-Item $PSCommandPath $runner
$summary=Join-Path $runDir 'summary.json';$runConfig=Join-Path $runDir 'run_config.json';$manifestWriter=Join-Path $repoRoot 'common\contracts\write_run_manifest.py'
[ordered]@{schema_version=1;run_id=$RunId;project='rf_quadrupole_collision_cooling';mode='rf_continuous_grounded_shield_n100_paired_comparison';project_root=$repoRoot;inputs=[ordered]@{analysis=$analysis;runner=$runner;candidate_events=$candidateEvents;candidate_manifest=$candidateManifest;reference_events=$referenceEvents;reference_manifest=$referenceManifest};parameters=[ordered]@{candidate_run_id=$CandidateRunId;reference_run_id=$ReferenceRunId;particle_count=100};formal_gate_passed=$false}|ConvertTo-Json -Depth 6|Set-Content $runConfig -Encoding UTF8
[ordered]@{schema_version=1;role='rf_continuous_shield_n100_comparison_summary';status='interrupted'}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;& $python $manifestWriter --run-config $runConfig --status interrupted --software 'Python 3.11';if($LASTEXITCODE -ne 0){throw 'Initial manifest failed.'}
try{& $python $analysis --candidate $candidateEvents --reference $referenceEvents --output-dir $resultDir;if($LASTEXITCODE -ne 0){throw 'N=100 paired analysis failed.'}}catch{[ordered]@{schema_version=1;role='rf_continuous_shield_n100_comparison_summary';status='failed';reason=$_.Exception.Message}|ConvertTo-Json|Set-Content $summary -Encoding UTF8;& $python $manifestWriter --run-config $runConfig --status failed --software 'Python 3.11';throw}
$metrics=Get-Content (Join-Path $resultDir 'rf_continuous_shield_n100_comparison_metrics.json') -Raw -Encoding UTF8|ConvertFrom-Json;[ordered]@{schema_version=1;role='rf_continuous_shield_n100_comparison_summary';status='success';acceptance_decision=$metrics.acceptance_decision}|ConvertTo-Json|Set-Content $summary -Encoding UTF8
$outputs=@((Join-Path $resultDir 'rf_continuous_shield_n100_paired_particles.csv'),(Join-Path $resultDir 'rf_continuous_shield_n100_comparison_metrics.json'),$summary);$args=@($manifestWriter,'--run-config',$runConfig,'--status','success','--software','Python 3.11');foreach($output in $outputs){$args+=@('--output',$output)};& $python @args;if($LASTEXITCODE -ne 0){throw 'Final manifest failed.'};Write-Output "STATUS=PASS RUN_ID=$RunId ACCEPTANCE_DECISION=$($metrics.acceptance_decision)"
