function verified = apply_wehnelt_contract_parameters(model, contract)
%APPLY_WEHNELT_CONTRACT_PARAMETERS Bind resolved values to GUI parameters.

    physical = contract.physical;
    filament = physical.filament;
    geometry = physical.geometry_mm;
    derived = contract.derived_geometry_mm;
    electrodes = physical.electrodes_V;
    numerical = contract.numerical;
    metric = physical.usable_final_state_metric;
    parameters = {
        'coil_rmaj', with_unit(filament.coil_major_radius_mm, 'mm'), ...
            'Filament coil major radius';
        'coil_rmin', with_unit(filament.wire_radius_mm, 'mm'), ...
            'Filament wire radius';
        'coil_turns', number_text(filament.turn_count), ...
            'Filament turn count';
        'coil_pitch', with_unit(filament.axial_pitch_mm, 'mm'), ...
            'Filament axial pitch';
        'coil_len', with_unit(derived.coil_length_mm, 'mm'), ...
            'Resolved filament length';
        'coil_xmin', with_unit(derived.coil_x_min_mm, 'mm'), ...
            'Resolved filament x start';
        'coil_zc', with_unit(filament.axis_center_z_mm, 'mm'), ...
            'Filament helix-axis z position';
        'filament_T', with_unit(filament.temperature_K, 'K'), ...
            'Filament emission temperature';
        'weh_skirt', with_unit(geometry.wehnelt_skirt_below_reference, 'mm'), ...
            'Wehnelt skirt below reference';
        'weh_gap', with_unit(geometry.wehnelt_cavity_ceiling_gap, 'mm'), ...
            'Wehnelt cavity ceiling gap';
        'weh_wall', with_unit(geometry.wehnelt_front_wall_thickness, 'mm'), ...
            'Wehnelt front wall thickness';
        'r_weh_cavity', with_unit(geometry.wehnelt_cavity_radius, 'mm'), ...
            'Wehnelt cavity radius';
        'r_weh_out', with_unit(geometry.wehnelt_outer_radius, 'mm'), ...
            'Wehnelt outer radius';
        'r_weh_hole', with_unit(geometry.wehnelt_aperture_radius, 'mm'), ...
            'Wehnelt aperture radius';
        'gap2', with_unit(geometry.wehnelt_to_anode_gap, 'mm'), ...
            'Wehnelt-to-anode gap';
        'r_an_out', with_unit(geometry.anode_outer_radius, 'mm'), ...
            'Anode outer radius';
        'r_an_hole', with_unit(geometry.anode_aperture_radius, 'mm'), ...
            'Anode aperture radius';
        'h_an', with_unit(geometry.anode_thickness, 'mm'), ...
            'Anode thickness';
        'drift', with_unit(geometry.post_anode_drift, 'mm'), ...
            'Post-anode drift';
        'r_domain', with_unit(geometry.vacuum_domain_radius, 'mm'), ...
            'Vacuum domain radius';
        'z_margin', with_unit(geometry.vacuum_margin_below_wehnelt, 'mm'), ...
            'Vacuum margin below Wehnelt';
        'chamfer_d', with_unit(geometry.electrode_chamfer_distance, 'mm'), ...
            'Electrode chamfer distance';
        'tool_overshoot', ...
            with_unit(geometry.boolean_tool_overshoot_each_side, 'mm'), ...
            'Boolean tool overshoot per side';
        'V_cathode', with_unit(electrodes.cathode, 'V'), ...
            'Cathode potential';
        'V_wehnelt', with_unit(electrodes.wehnelt, 'V'), ...
            'Wehnelt potential';
        'V_anode', with_unit(electrodes.anode, 'V'), ...
            'Anode potential';
        'z_weh_bot', with_unit(derived.wehnelt_bottom_z_mm, 'mm'), ...
            'Resolved Wehnelt bottom';
        'z_weh_ceil', ...
            with_unit(derived.wehnelt_cavity_ceiling_z_mm, 'mm'), ...
            'Resolved Wehnelt cavity ceiling';
        'z_weh_top', with_unit(derived.wehnelt_top_z_mm, 'mm'), ...
            'Resolved Wehnelt top';
        'z_an_bot', with_unit(derived.anode_bottom_z_mm, 'mm'), ...
            'Resolved anode bottom';
        'z_an_top', with_unit(derived.anode_top_z_mm, 'mm'), ...
            'Resolved anode top';
        'z_dom_bot', with_unit(derived.vacuum_domain_bottom_z_mm, 'mm'), ...
            'Resolved vacuum-domain bottom';
        'z_dom_top', with_unit(derived.vacuum_domain_top_z_mm, 'mm'), ...
            'Resolved vacuum-domain top';
        'mesh_coil_hmax', ...
            with_unit(numerical.mesh.filament_surface_hmax_mm, 'mm'), ...
            'Filament local mesh maximum';
        'mesh_coil_hmin', ...
            with_unit(numerical.mesh.filament_surface_hmin_mm, 'mm'), ...
            'Filament local mesh minimum';
        'mesh_hgrad', ...
            number_text(numerical.mesh.maximum_element_growth_rate), ...
            'Maximum element growth rate';
        'particle_t_start', ...
            with_unit(numerical.particle_time_ns.start, 'ns'), ...
            'Particle time start';
        'particle_t_step', ...
            with_unit(numerical.particle_time_ns.step, 'ns'), ...
            'Particle time step';
        'particle_t_end', ...
            with_unit(numerical.particle_time_ns.end, 'ns'), ...
            'Particle time end';
        'usable_energy_min', ...
            with_unit(metric.usable_energy_min_eV, 'eV'), ...
            'Usable-electron lower energy bound';
        'usable_energy_max', ...
            with_unit(metric.usable_energy_max_eV, 'eV'), ...
            'Usable-electron upper energy bound'
    };

    parameterGroup = model.param;
    for index = 1:size(parameters, 1)
        parameterGroup.set(parameters{index, 1}, parameters{index, 2}, ...
            parameters{index, 3});
    end
    for index = 1:size(parameters, 1)
        actual = char(parameterGroup.get(parameters{index, 1}));
        assert(strcmp(actual, parameters{index, 2}), ...
            'COMSOL parameter %s is not bound to the resolved contract.', ...
            parameters{index, 1});
    end
    verified = true;
end

function text = with_unit(value, unit)
    text = sprintf('%.17g[%s]', double(value), unit);
end

function text = number_text(value)
    text = sprintf('%.17g', double(value));
end
