function contract = load_wehnelt_contract(contractPath)
%LOAD_WEHNELT_CONTRACT Load a validated resolved Wehnelt contract.
% The tracked resolved file is generated and freshness-checked by the Python
% resolver. This loader has no physical or numerical fallback values.

    arguments
        contractPath (1, :) char
    end

    assert(isfile(contractPath), ...
        'Resolved Wehnelt contract not found: %s', contractPath);
    contract = jsondecode(fileread(contractPath));

    assert(contract.schema_version == 1, ...
        'Unsupported resolved Wehnelt schema version.');
    assert(strcmp(contract.role, ...
        'wehnelt_electron_gun_resolved_contract'), ...
        'Resolved Wehnelt contract role mismatch.');
    assert(strcmp(contract.project_id, 'wehnelt_electron_gun'), ...
        'Resolved Wehnelt project identity mismatch.');
    assert(strcmp(contract.model_id, ...
        'wehnelt.transverse_helical_filament.thermal_transport.v1'), ...
        'Resolved Wehnelt model identity mismatch.');
    assert(strcmp(contract.physical.project_id, contract.project_id), ...
        'Physical/resolved project identities disagree.');
    assert(strcmp(contract.physical.model_id, contract.model_id), ...
        'Physical/resolved model identities disagree.');
    assert(strcmp(contract.source_identity.hash_algorithm, 'SHA-256'), ...
        'Resolved Wehnelt source hash algorithm mismatch.');
    assert(~isempty(contract.source_identity.baseline_sha256) && ...
        ~isempty(contract.source_identity.numerical_modes_sha256), ...
        'Resolved Wehnelt source identities are missing.');

    capability = contract.physical.capability;
    assert(~capability.imaging_quality_claim_allowed, ...
        'The transverse prototype cannot claim imaging quality.');
    assert(~capability.formal_performance_claim_allowed, ...
        'The current prototype cannot claim formal performance.');
    filament = contract.physical.filament;
    assert(strcmp(filament.material_identity, 'tungsten') && ...
        strcmp(filament.material_model_scope, ...
        'identity_only_no_thermionic_current_model'), ...
        'Resolved filament material identity/scope mismatch.');
    particle = contract.physical.particle;
    assert(strcmp(particle.species_id, 'electron') && ...
        isfinite(particle.mass_kg) && particle.mass_kg > 0 && ...
        particle.charge_state == -1 && ...
        isfinite(particle.charge_C) && particle.charge_C < 0, ...
        'Resolved electron species, mass, or charge is invalid.');
    emission = contract.physical.emission_model;
    assert(strcmp(emission.release_surface_role, ...
        'entire_filament_surface') && ...
        strcmp(emission.velocity_distribution, 'Thermal') && ...
        strcmp(emission.particle_weighting, ...
        'unweighted_test_particles') && ...
        ~emission.physical_particle_weight_available && ...
        ~emission.beam_current_supported, ...
        'Resolved emission-model assumptions are invalid.');
    terminal = contract.physical.terminal_outcomes;
    assert(strcmp(terminal.wall_condition, 'Freeze') && ...
        strcmp(terminal.nonfinite_final_position_outcome, ...
        'unclassified_terminal_state') && ...
        ~terminal.wall_loss_attribution_supported, ...
        'Resolved terminal-outcome assumptions are invalid.');
    metric = contract.physical.usable_final_state_metric;
    assert(strcmp(metric.valid_state_rule, ...
        'finite_final_particle_position') && ...
        isfinite(metric.usable_energy_min_eV) && ...
        isfinite(metric.usable_energy_max_eV) && ...
        metric.usable_energy_min_eV < metric.usable_energy_max_eV && ...
        ~metric.historical_value_is_current_evidence, ...
        'Resolved usable-final-state metric is invalid.');
    coordinate = contract.physical.coordinate_convention;
    assert(strcmp(coordinate.frame_id, ...
        'wehnelt_electron_gun_component'), ...
        'Resolved Wehnelt frame identity mismatch.');
    assert(strcmp(coordinate.beam_axis, '+z') && ...
        strcmp(coordinate.filament_helix_axis, '+x'), ...
        'Resolved Wehnelt axis convention mismatch.');

    derived = contract.derived_geometry_mm;
    assert(derived.coil_x_min_mm < derived.coil_x_max_mm, ...
        'Resolved filament axial extent is invalid.');
    assert(derived.wehnelt_bottom_z_mm < ...
        derived.wehnelt_cavity_ceiling_z_mm && ...
        derived.wehnelt_cavity_ceiling_z_mm < ...
        derived.wehnelt_top_z_mm, ...
        'Resolved Wehnelt axial geometry is invalid.');
    assert(derived.wehnelt_top_z_mm < derived.anode_bottom_z_mm && ...
        derived.anode_bottom_z_mm < derived.anode_top_z_mm, ...
        'Resolved anode axial geometry is invalid.');
    assert(derived.vacuum_domain_bottom_z_mm < ...
        derived.wehnelt_bottom_z_mm && ...
        derived.vacuum_domain_top_z_mm > derived.anode_top_z_mm, ...
        'Resolved vacuum-domain extent is invalid.');

    time = contract.numerical.particle_time_ns;
    assert(time.start == 0 && time.step > 0 && time.step <= time.end, ...
        'Resolved particle time range is invalid.');
    assert(strcmp(contract.numerical.mesh.element_type, 'FreeTet'), ...
        'The current COMSOL builder supports only FreeTet.');
    assert(~contract.numerical.candidate_evidence_allowed && ...
        ~contract.evidence.candidate_evidence_allowed, ...
        'Current Wehnelt modes cannot claim Candidate evidence.');
    minimumCount = contract.evidence.minimum_particle_count;
    if isempty(minimumCount)
        assert(strcmp(contract.numerical.execution_mode, 'build_only'), ...
            'A mode without an evidence minimum must remain build-only.');
    else
        assert(strcmp(contract.numerical.execution_mode, 'full'), ...
            'A functional particle-count mode must execute the full model.');
        assert(contract.evidence.requested_particle_count >= ...
            minimumCount, ...
            'Functional evidence particle count is below the contract minimum.');
    end
    sampling = contract.numerical.particle_sampling;
    assert(isempty(sampling.random_seed) && ...
        strcmp(sampling.seed_control, 'comsol_default_unfrozen') && ...
        ~sampling.reproducible_particle_realization, ...
        'Resolved particle sampling overstates reproducibility.');
end
