function contract = load_ei_source_contract(contractPath)
%LOAD_EI_SOURCE_CONTRACT Load a validated, resolved EI-source contract.
% This loader intentionally has no numerical fallbacks. The Python resolver
% owns schema/range validation; MATLAB rechecks identity and fields required
% by the COMSOL builder so a stale or unrelated contract fails visibly.

    arguments
        contractPath (1, :) char
    end

    assert(isfile(contractPath), 'Resolved EI-source contract not found: %s', ...
        contractPath);
    contract = jsondecode(fileread(contractPath));

    assert(contract.schema_version == 1, ...
        'Unsupported resolved EI-source schema version.');
    assert(strcmp(contract.role, ...
        'electron_impact_ion_source_resolved_contract'), ...
        'Resolved EI-source contract role mismatch.');
    assert(strcmp(contract.project_id, 'electron_impact_ion_source'), ...
        'Resolved EI-source project identity mismatch.');
    assert(strcmp(contract.model_id, ...
        'ei_source.long_thin_apertured_tube.yield_feasibility.v1'), ...
        'Resolved EI-source model identity mismatch.');
    assert(strcmp(contract.physical.project_id, contract.project_id), ...
        'Physical/resolved project identities disagree.');
    assert(strcmp(contract.physical.model_id, contract.model_id), ...
        'Physical/resolved model identities disagree.');
    assert(~contract.physical.capability.heavy_ion_source_claim_allowed, ...
        'This prototype contract cannot claim a heavy-ion source.');
    assert(~contract.physical.ionization.release_ionized_particle, ...
        'This prototype cannot release a tracked heavy-ion species.');

    geometry = contract.physical.geometry_mm;
    assert(geometry.electrode_aperture_radius < geometry.tube_bore_radius, ...
        'Electrode aperture must remain inside the tube bore.');
    assert(geometry.release_volume_radius <= ...
        geometry.electrode_aperture_radius, ...
        'Release volume radius must fit through the aperture.');
    assert(contract.numerical.time_ns.step <= contract.numerical.time_ns.end, ...
        'Time step cannot exceed the simulation end time.');
    assert(strcmp(contract.numerical.solver.time_integrator, 'BDF'), ...
        'The current builder supports only the resolved BDF integrator.');

    if contract.numerical.candidate_evidence_allowed
        assert(contract.evidence.requested_particle_count >= ...
            contract.evidence.minimum_particle_count, ...
            'Functional evidence particle count is below the contract minimum.');
    else
        assert(strcmp(contract.numerical.execution_mode, 'build_only'), ...
            'Evidence-ineligible mode must remain build-only.');
    end
end
